-- Sample Query for Karen's Dataset (stored at DSC_PLBI_DB.APP_AUTO_DEV.POL_UW_DECOUPLING)
SELECT POL_ID, RISK_ST_ABBR, 
ORIG_POL_EFF_DT, 
POL_EFF_DT,
CASE WHEN ORIG_POL_EFF_DT >= DATEADD(MONTH, -6, CURRENT_DATE())
THEN 'NB' ELSE 'Renewal' END AS POL_TYPE,
TRANS_STAT_DESC, CLEAN_DIRTY_CD,
POL_TTL_SPEED_MNR_VIO_CNT, POL_TTL_NSPD_MNR_VIO_CNT,
UW_ELIG_POL_AFA_CNT,
UW_ELIG_POL_NAF_ACCID_CNT,
UW_ELIG_POL_COMP_CLM_CNT,
UW_ELIG_POL_MLTRY_PRMT_CNT,
UW_ELIG_POL_PERM_USE_ACCID_CNT,
UW_ELIG_RENTL_TOW_GLASS_CNT,
(UW_ELIG_POL_AFA_CNT + UW_ELIG_POL_NAF_ACCID_CNT + 
UW_ELIG_POL_COMP_CLM_CNT + UW_ELIG_POL_MLTRY_PRMT_CNT + UW_ELIG_POL_PERM_USE_ACCID_CNT) AS DERIVED_TTL_ACCID_VIO_COMP_CNT,
CASE WHEN DERIVED_TTL_ACCID_VIO_COMP_CNT = 0 THEN 'No Acc/Viol/Comp' ELSE 'Yes Acc/Viol/Comp' END AS DERIVED_YES_NO_FLAG
FROM "PRD_PL_DB"."APP_DCPA_DM"."AUTO_POLICY_LATST_VW"
WHERE POL_EFF_DT >= '2024-07-11' 
AND RISK_ST_ABBR = 'AZ'

-------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Main Query (joining to Auto Operational Loss)
SELECT 
UW_AUTO.POL_ID, 
EARNED_MONTH,
MIN(UW_AUTO.RISK_ST_ABBR) AS RISK_ST_ABBR,
MIN(UW_AUTO.ORIG_POL_EFF_DT) AS ORIG_POL_EFF_DT,
MIN(UW_AUTO.POL_EFF_DT) AS LATEST_POL_EFF_DT,
MIN(UW_AUTO.TRANS_STAT_DESC) AS TRANS_STAT_DESC,
MIN(UW_AUTO.POL_TYPE) AS POL_TYPE,
MIN(UW_AUTO.CLEAN_DIRTY_CD) AS CLEAN_DIRTY_CD,
MIN(UW_AUTO.POL_TTL_SPEED_MNR_VIO_CNT) AS POL_TTL_SPEED_MNR_VIO_CNT,
MIN(UW_AUTO.POL_TTL_NSPD_MNR_VIO_CNT) AS POL_TTL_NSPD_MNR_VIO_CNT,
MIN(UW_AUTO.UW_ELIG_POL_AFA_CNT) AS UW_ELIG_POL_AFA_CNT,
MIN(UW_AUTO.UW_ELIG_POL_NAF_ACCID_CNT) AS UW_ELIG_POL_NAF_ACCID_CNT,
MIN(UW_AUTO.UW_ELIG_POL_COMP_CLM_CNT) AS UW_ELIG_POL_COMP_CLM_CNT,
MIN(UW_AUTO.UW_ELIG_POL_MLTRY_PRMT_CNT) AS UW_ELIG_POL_MLTY_PRMT_CNT,
MIN(UW_AUTO.UW_ELIG_POL_PERM_USE_ACCID_CNT) AS UW_ELIG_POL_PERM_USE_ACCID_CNT,
MIN(UW_AUTO.UW_ELIG_RENTL_TOW_GLASS_CNT) AS UW_ELIG_RENTL_TOW_GLASS_CNT,
MIN(UW_AUTO.DERIVED_TTL_ACCID_VIO_COMP_CNT) AS DERIVED_TTL_ACCID_VIO_COMP_CNT,
MIN(UW_AUTO.DERIVED_YES_NO_FLAG) AS DERIVED_YES_NO_FLAG,
SUM(AUTO_OP_LOSS.INCUR_CLM_CNT_XCAT) AS INCUR_CLM_CNT_XCAT,
SUM(AUTO_OP_LOSS.DERIV_INCUR_LOSS_AMT_XCAT) AS DERIV_INCUR_LOSS_AMT_XCAT,
SUM(AUTO_OP_LOSS.GLASS_TOW_INCUR_CLM_CNT) AS GLASS_TOW_INCUR_CLM_CNT,
SUM(AUTO_OP_LOSS.GLASS_TOW_INCUR_LOSS_AMT) AS GLASS_TOW_INCUR_LOSS_AMT,
SUM(AUTO_OP_LOSS.DERIV_ADJ_EP_AMT) AS EP,                 
SUM(AUTO_OP_LOSS.RERATED_EP_EPAPR_AMT) AS EPAPR,            
DAY(LAST_DAY(TO_DATE(EARNED_MONTH || '01', 'YYYYMMDD'))) / 
IFF(MOD(SUBSTR(EARNED_MONTH, 1, 4), 4) = 0 AND (MOD(SUBSTR(EARNED_MONTH, 1, 4), 100) != 0 OR MOD(SUBSTR(EARNED_MONTH, 1, 4), 400) = 0), 366, 365)
AS EE                                                    
FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_OPERATIONAL_LOSS" AS AUTO_OP_LOSS
JOIN DSC_PLBI_DB.APP_AUTO_DEV.POL_UW_DECOUPLING AS UW_AUTO
ON CAST(AUTO_OP_LOSS.POL_ID AS VARCHAR) = CAST(UW_AUTO.POL_ID AS VARCHAR)
AND AUTO_OP_LOSS.POL_EFF_DT = UW_AUTO.POL_EFF_DT
WHERE COV_TYPE_ABBR != 'PUP'
AND RISK_ST_ABBR IN ('AZ', 'IN', 'MO', 'TN')
AND EARNED_MONTH >= '202407' 
GROUP BY UW_AUTO.POL_ID, EARNED_MONTH 
ORDER BY UW_AUTO.POL_ID, EARNED_MONTH   

-------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Metrics Check
SELECT 
CASE WHEN CLEAN_DIRTY_CD = 'C' AND DERIVED_YES_NO_FLAG = 'No Acc/Viol/Comp' THEN 'Clean/Clean'
WHEN CLEAN_DIRTY_CD = 'C' AND DERIVED_YES_NO_FLAG = 'Yes Acc/Viol/Comp' THEN 'Clean/Dirty'
ELSE 'Dirty/Dirty' END AS "CHARGEABILITY/UW", 
EARNED_MONTH, 
SUM(SUM(DERIV_INCUR_LOSS_AMT_XCAT)) OVER (PARTITION BY "CHARGEABILITY/UW" ORDER BY EARNED_MONTH) AS CUMULATIVE_LOSS, 
SUM(SUM(EPAPR)) OVER (PARTITION BY "CHARGEABILITY/UW" ORDER BY EARNED_MONTH) AS CUMULATIVE_TTL_EPAPR, 
SUM(SUM(DERIV_INCUR_LOSS_AMT_XCAT)) OVER (PARTITION BY "CHARGEABILITY/UW" ORDER BY EARNED_MONTH) / 
SUM(SUM(EPAPR)) OVER (PARTITION BY "CHARGEABILITY/UW" ORDER BY EARNED_MONTH) AS CUMULATIVE_LOSS_RATIO, 
SUM(SUM(EE)) OVER (PARTITION BY "CHARGEABILITY/UW" ORDER BY EARNED_MONTH) AS CUMULATIVE_TTL_EE, 
COUNT(DISTINCT POL_ID) AS CNT
-- FROM DSC_PLBI_DB.APP_AUTO_DEV.FULL_UW_DECOUPLING_DATA
FROM USER_DB.AD1_PA08042.DATA_JULY
WHERE RISK_ST_ABBR = 'IN'
-- AND POL_TYPE = 'Renewal'
GROUP BY "CHARGEABILITY/UW", EARNED_MONTH
ORDER BY EARNED_MONTH, "CHARGEABILITY/UW";

-------------------------------------------------------------------------------------------------------------------------------------------------------------

-- LRR Check
SELECT 
RISK_ST_ABBR,
CASE WHEN CLEAN_DIRTY_CD = 'C' AND DERIVED_YES_NO_FLAG = 'No Acc/Viol/Comp' THEN 'Clean/Clean'
WHEN CLEAN_DIRTY_CD = 'C' AND DERIVED_YES_NO_FLAG = 'Yes Acc/Viol/Comp' THEN 'Clean/Dirty'
ELSE 'Dirty/Dirty' END AS "CHARGEABILITY/UW", 
POL_TYPE,
ROUND((SUM(DERIV_INCUR_LOSS_AMT_XCAT) / SUM(EPAPR)) /
(SUM(SUM(DERIV_INCUR_LOSS_AMT_XCAT)) OVER (PARTITION BY RISK_ST_ABBR) / SUM(SUM(EPAPR)) OVER (PARTITION BY RISK_ST_ABBR)), 2) AS LRR
FROM DSC_PLBI_DB.APP_AUTO_DEV.FULL_UW_DECOUPLING_DATA
-- FROM USER_DB.AD1_PA08042.DATA_JULY
WHERE RISK_ST_ABBR = 'IN'
AND POL_TYPE = 'Renewal'
GROUP BY RISK_ST_ABBR, "CHARGEABILITY/UW", POL_TYPE
ORDER BY RISK_ST_ABBR, "CHARGEABILITY/UW", POL_TYPE;