-- Drips Queries 3/31
-- Creation of Auto Drips Table
CREATE OR REPLACE TRANSIENT TABLE USER_DB.AD1_PA08042.AUTO_DRIPS
AS
(
    WITH auto_drips AS
    (
        SELECT *,
        CASE WHEN CTRL_TEST_CD = 'C' THEN 1 ELSE 2 END AS EXCLUDE_TEST
        FROM PRD_PL_DB.APP_DCPA_DM.DRIPS_EXTRACT
        WHERE LOI_CD = 'AUTO'
        AND BILL_EXTRCT_TYP_DESC = 'RecordInsert'
        AND DO_NOT_CALL_CNTCT_LIST_IND = 'N'
    ),

    /* Excludes auto policies that are both Control and Test */
    exclude_dups AS
    (
        SELECT POL_ID, AVG(EXCLUDE_TEST) AS CNT FROM auto_drips
        GROUP BY POL_ID
        HAVING CNT = 1 OR CNT = 2
    ),

    /* Keeps records that are only in one group (Control or Test) */
    final_auto_drips AS
    (
        SELECT * from auto_drips
        WHERE POL_ID IN (SELECT POL_ID FROM exclude_dups)
    ),
    
    /* Labels every necessary record in Home Persistency */
    ap_labeled AS
    (
        SELECT * ,
        ROW_NUMBER() OVER (PARTITION BY POL_ID ORDER BY POL_EFF_DT DESC) AS auto_rn,
        FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_PERSISTENCY_COMBINED"
        WHERE POL_ID IN (SELECT POL_ID FROM exclude_dups)
    ),
    
    /* Takes most recent record for each necessary POL_ID */
    ap_filtered AS
    (
        SELECT * FROM ap_labeled WHERE auto_rn = 1
    ),
    
    billing_data AS
    (
    SELECT ACCOUNT.BILL_ACCT_ID
          ,TERM.POL_TERM_ID
          ,TERM.POL_ID
          ,TERM.POL_TERM_EFF_DT POL_EFF_DT
          ,TERM.POL_TERM_EXP_DT POL_EXP_DT
          ,ACCOUNT.BILL_ACCT_PLAN_TYP_CD
          ,ACCOUNT.BILL_ACCT_PLAN_TYP_DESC
          ,TERM_DATA.BILL_INSTAL_TYP_DESC
    FROM  PRD_PL_DB.APP_DCPA_BILL_CURATE.DC_BIL_ACCOUNT_LTST_VW ACCOUNT,
          PRD_PL_DB.APP_DCPA_BILL_CURATE.DC_BIL_POLICYTERM_LTST_VW TERM,
          PRD_PL_DB.APP_DCPA_BILL_CURATE.DC_BIL_POLICYTERMDATA_LTST_VW TERM_DATA
    WHERE ACCOUNT.BILL_ACCT_ID = TERM.ORIG_BILL_ACCT_ID
    AND   TERM.POL_TERM_ID = TERM_DATA.POL_TERM_ID
    )
    
    SELECT fad.POL_ID,
    fad.CTRL_TEST_CD,
    fad.BILL_INSTAL_TYP_DESC, 
    ap.POL_EFF_DT,
    ap.CANCEL_FLAG,
    ap.POL_TRANS_EFF_DT AS LATST_TRANS_DT,
    ap.TRANS_TYP_DESC,
    CASE WHEN
    bd.BILL_ACCT_PLAN_TYP_CD IN ('HIG_ACT_A1','HIG_ACT_A2','HIG_ACT_A3','HIG_ACT_A4') THEN 'Auto Pay'
    ELSE 'On Demand' END AS PYMT_TYPE,
    ap.ATR_E_FLAT,
    ap.ATR_E_30,
    ap.CANCEL_E_FLAT,
    ap.CANCEL_E_30,
    ap.RISK_ST_ABBR
    FROM final_auto_drips AS fad
    JOIN ap_filtered AS ap
    ON fad.POL_ID = ap.POL_ID
    JOIN billing_data bd
    ON ap.POL_ID = bd.POL_ID AND ap.POL_EFF_DT = bd.POL_EFF_DT
);

DROP TABLE USER_DB.AD1_PA08042.AUTO_DRIPS;

----------------------------------------- Excel Sheet -----------------------------------------
-- Queries for Excel Sheet
-- E+0 Query
SELECT CTRL_TEST_CD,
BILL_INSTAL_TYP_DESC,
CASE 
WHEN ATR_E_FLAT = 1 AND CANCEL_E_FLAT = 0 THEN 'Active'
WHEN ATR_E_FLAT = 1 AND CANCEL_E_FLAT = 1 THEN 'Cancel'
WHEN ATR_E_FLAT = 0 AND CANCEL_E_FLAT = 0 AND CANCEL_FLAG = 1 THEN 'Cancel'
ELSE 'Pending' END AS STATUS,
COUNT(DISTINCT POL_ID) AS CNT
FROM USER_DB.AD1_PA08042.AUTO_DRIPS
WHERE PYMT_TYPE = 'On Demand' AND BILL_INSTAL_TYP_DESC = 'Monthly Installments'
-- AND POL_EFF_DT BETWEEN '2024-12-12' AND '2024-12-19' -- Week 1
-- AND POL_EFF_DT BETWEEN '2024-12-20' AND '2024-12-27' -- Week 2
-- AND POL_EFF_DT BETWEEN '2024-12-28' AND '2025-01-04' -- Week 3
-- AND POL_EFF_DT BETWEEN '2025-01-05' AND '2025-01-12' -- Week 4
-- AND POL_EFF_DT BETWEEN '2025-01-13' AND '2025-01-20' -- Week 5
-- AND POL_EFF_DT BETWEEN '2025-01-21' AND '2025-01-28' -- Week 6
-- AND POL_EFF_DT BETWEEN '2025-01-29' AND '2025-02-05' -- Week 7
-- AND POL_EFF_DT BETWEEN '2025-02-06' AND '2025-02-13' -- Week 8
-- AND POL_EFF_DT BETWEEN '2025-02-14' AND '2025-02-21' -- Week 9
-- AND POL_EFF_DT BETWEEN '2025-02-22' AND '2025-03-01' -- Week 10
-- AND POL_EFF_DT BETWEEN '2025-03-02' AND '2025-03-09' -- Week 11
-- AND POL_EFF_DT BETWEEN '2025-03-10' AND '2025-03-15' -- Week 12
-- AND POL_EFF_DT BETWEEN '2024-12-12' AND '2025-02-02' -- 50/50
-- AND POL_EFF_DT BETWEEN '2025-02-03' AND '2025-03-15' -- 90/10
AND POL_EFF_DT BETWEEN '2024-12-12' AND '2025-03-15' -- Full Roll-Up
AND RISK_ST_ABBR NOT IN ('AZ', 'OH', 'WV') 
GROUP BY CTRL_TEST_CD, BILL_INSTAL_TYP_DESC, STATUS
ORDER BY BILL_INSTAL_TYP_DESC, CTRL_TEST_CD, STATUS;

-- E+30 Query
SELECT CTRL_TEST_CD,
BILL_INSTAL_TYP_DESC,
CASE 
WHEN ATR_E_30 = 1 AND CANCEL_E_30 = 0 THEN 'Active'
WHEN ATR_E_30 = 1 AND CANCEL_E_30 = 1 THEN 'Cancel'
WHEN ATR_E_30 = 0 AND CANCEL_E_30 = 0 AND CANCEL_FLAG = 1 THEN 'Cancel'
ELSE 'Pending' END AS STATUS,
COUNT(DISTINCT POL_ID) AS CNT
FROM USER_DB.AD1_PA08042.AUTO_DRIPS
WHERE PYMT_TYPE = 'On Demand' AND BILL_INSTAL_TYP_DESC = 'Monthly Installments'
-- AND POL_EFF_DT BETWEEN '2024-12-12' AND '2024-12-19' -- Week 1
-- AND POL_EFF_DT BETWEEN '2024-12-20' AND '2024-12-27' -- Week 2
-- AND POL_EFF_DT BETWEEN '2024-12-28' AND '2025-01-04' -- Week 3
-- AND POL_EFF_DT BETWEEN '2025-01-05' AND '2025-01-12' -- Week 4
-- AND POL_EFF_DT BETWEEN '2025-01-13' AND '2025-01-20' -- Week 5
-- AND POL_EFF_DT BETWEEN '2025-01-21' AND '2025-01-28' -- Week 6
-- AND POL_EFF_DT BETWEEN '2025-01-29' AND '2025-02-05' -- Week 7
-- AND POL_EFF_DT BETWEEN '2025-02-06' AND '2025-02-13' -- Week 8
-- AND POL_EFF_DT BETWEEN '2025-02-14' AND '2025-02-21' -- Week 9
-- AND POL_EFF_DT BETWEEN '2025-02-22' AND '2025-02-28' -- Week 10
-- AND POL_EFF_DT BETWEEN '2024-12-12' AND '2025-02-02' -- 50/50
-- AND POL_EFF_DT BETWEEN '2025-02-03' AND '2025-02-28' -- 90/10
AND POL_EFF_DT BETWEEN '2024-12-12' AND '2025-02-28' -- Full Roll-Up
AND RISK_ST_ABBR IN ('AZ', 'OH', 'WV') 
GROUP BY CTRL_TEST_CD, BILL_INSTAL_TYP_DESC, STATUS
ORDER BY BILL_INSTAL_TYP_DESC, CTRL_TEST_CD, STATUS;

-- Control and Test Query
WITH start_data AS
(
    SELECT * FROM PRD_PL_DB.APP_DCPA_DM.DRIPS_EXTRACT
    WHERE LOI_CD = 'AUTO'
    AND BILL_EXTRCT_TYP_DESC = 'RecordInsert'
    AND DO_NOT_CALL_CNTCT_LIST_IND = 'N'
),

agg AS
(
    SELECT POL_ID, COUNT(DISTINCT CTRL_TEST_CD) AS CNT
    FROM start_data
    GROUP BY POL_ID
)

SELECT CASE WHEN CNT > 1 THEN 'Both' ELSE 'One' END CT_CHECK,
COUNT(DISTINCT POL_ID) AS CNT_POL
FROM agg
GROUP BY CT_CHECK;

----------------------------------------- Policy Count Slide -----------------------------------------

WITH ap AS
(
    SELECT *,
    ROW_NUMBER() OVER (PARTITION BY POL_ID ORDER BY POL_EFF_DT DESC) AS auto_rn,
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_PERSISTENCY_COMBINED"
),

inforce_auto AS
(
    SELECT * FROM ap
    WHERE auto_rn = 1 AND CANCEL_FLAG = 0 
    AND NEWCO_IND = 'Y' AND POL_EFF_DT >= DATE(DATEADD(MONTH, -6, GETDATE()))
    AND POL_QTE_STAT_DESC = 'InForce'
),

billing_data AS
(
    SELECT ACCOUNT.BILL_ACCT_ID
      ,TERM.POL_TERM_ID
      ,TERM.POL_ID
      ,TERM.POL_TERM_EFF_DT POL_EFF_DT
      ,TERM.POL_TERM_EXP_DT POL_EXP_DT
      ,ACCOUNT.BILL_ACCT_PLAN_TYP_CD
      ,ACCOUNT.BILL_ACCT_PLAN_TYP_DESC
      ,TERM_DATA.BILL_INSTAL_TYP_DESC
    FROM  PRD_PL_DB.APP_DCPA_BILL_CURATE.DC_BIL_ACCOUNT_LTST_VW ACCOUNT,
      PRD_PL_DB.APP_DCPA_BILL_CURATE.DC_BIL_POLICYTERM_LTST_VW TERM,
      PRD_PL_DB.APP_DCPA_BILL_CURATE.DC_BIL_POLICYTERMDATA_LTST_VW TERM_DATA
    WHERE ACCOUNT.BILL_ACCT_ID = TERM.ORIG_BILL_ACCT_ID
    AND   TERM.POL_TERM_ID = TERM_DATA.POL_TERM_ID
),

joined AS
(
    SELECT 
    ia.POL_ID,
    ia.POL_EFF_DT,
    ia.RISK_ST_ABBR,
    bd.BILL_ACCT_PLAN_TYP_CD,
    bd.BILL_INSTAL_TYP_DESC
    FROM inforce_auto ia
    JOIN billing_data bd 
    ON ia.POL_ID = bd.POL_ID AND ia.POL_EFF_DT = bd.POL_EFF_DT
),

drips_window AS
(
    SELECT * 
    FROM joined
    WHERE (POL_EFF_DT BETWEEN '2024-12-12' AND '2025-03-31' AND BILL_INSTAL_TYP_DESC = 'Full Pay')
    OR (BILL_INSTAL_TYP_DESC = 'Monthly Installments' AND POL_EFF_DT >= '2024-09-30')
)

-- Total Inforce (Box 1)
-- SELECT CASE WHEN RISK_ST_ABBR IN ('AZ', 'OH', 'WV') THEN 'Non-Lapse' ELSE 'Lapse' END AS STATE_LEGISLATION,
-- COUNT(DISTINCT POL_ID) AS CNT
-- FROM inforce_auto
-- GROUP BY STATE_LEGISLATION;

-- Drips Window (Box 2)
-- SELECT CASE WHEN RISK_ST_ABBR IN ('AZ', 'OH', 'WV') THEN 'Non-Lapse' ELSE 'Lapse' END AS STATE_LEGISLATION,
-- COUNT(DISTINCT POL_ID) AS CNT
-- FROM drips_window
-- GROUP BY STATE_LEGISLATION;

-- Eligible vs. Ineligible (Boxes 3-6) (Also Box 2)
SELECT 
CASE WHEN RISK_ST_ABBR IN ('AZ', 'OH', 'WV') THEN 'Non-Lapse' ELSE 'Lapse' END AS STATE_LEGISLATION,
CASE WHEN BILL_INSTAL_TYP_DESC = 'Full Pay' 
AND BILL_ACCT_PLAN_TYP_CD IN ('HIG_ACT_A1','HIG_ACT_A2','HIG_ACT_A3','HIG_ACT_A4') THEN 'Auto Full Pay'
WHEN BILL_INSTAL_TYP_DESC = 'Full Pay' 
AND BILL_ACCT_PLAN_TYP_CD IN ('HIG_ACT_A6','HIG_ACT_A7') THEN 'On Demand Full Pay'
WHEN BILL_INSTAL_TYP_DESC = 'Monthly Installments' 
AND BILL_ACCT_PLAN_TYP_CD IN ('HIG_ACT_A1','HIG_ACT_A2','HIG_ACT_A3','HIG_ACT_A4') THEN 'Auto Monthly Pay'
WHEN BILL_INSTAL_TYP_DESC = 'Monthly Installments' 
AND BILL_ACCT_PLAN_TYP_CD IN ('HIG_ACT_A6','HIG_ACT_A7') THEN 'On Demand Monthly Pay'
ELSE 'N/A' END AS BUCKET,
COUNT(DISTINCT POL_ID) AS CNT
FROM joined
-- FROM drips_window
GROUP BY STATE_LEGISLATION, BUCKET
ORDER BY STATE_LEGISLATION, BUCKET;

-- Exclusions (Box 8)
WITH full_data AS
(
    SELECT *, COUNT(DISTINCT CTRL_TEST_CD) OVER (PARTITION BY POL_ID) AS CONTROL_TEST_CHECK
    FROM PRD_PL_DB.APP_DCPA_DM.DRIPS_EXTRACT
    WHERE LOI_CD = 'AUTO'
    AND BILL_EXTRCT_TYP_DESC = 'RecordInsert'
    AND DO_NOT_CALL_CNTCT_LIST_IND = 'N'
),

add_state AS
(
    SELECT fd.*, ap.RISK_ST_ABBR
    FROM full_data AS fd
    JOIN "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_PERSISTENCY_COMBINED" AS ap
    USING (POL_ID, POL_EFF_DT)
)

SELECT CASE WHEN RISK_ST_ABBR IN ('AZ', 'OH', 'WV') THEN 'Non-Lapse' ELSE 'Lapse' END AS STATE_LEGISLATION,
COUNT(DISTINCT POL_ID) AS CNT
FROM add_state
WHERE CONTROL_TEST_CHECK > 1
GROUP BY STATE_LEGISLATION;

-- Campaign Start (Boxes 9-12)
SELECT CASE WHEN RISK_ST_ABBR IN ('AZ', 'OH', 'WV') THEN 'Non-Lapse' ELSE 'Lapse' END AS STATE_LEGISLATION,
CONCAT(PYMT_TYPE, ' ', BILL_INSTAL_TYP_DESC) AS PAYMENT_BUCKET,
COUNT(DISTINCT POL_ID) AS CNT
FROM USER_DB.AD1_PA08042.AUTO_DRIPS
GROUP BY STATE_LEGISLATION, PAYMENT_BUCKET
ORDER BY STATE_LEGISLATION, PAYMENT_BUCKET;

-- Monthly Lapse
SELECT CTRL_TEST_CD,
BILL_INSTAL_TYP_DESC,
CASE 
WHEN ATR_E_FLAT = 1 AND CANCEL_E_FLAT = 0 THEN 'Active'
WHEN ATR_E_FLAT = 1 AND CANCEL_E_FLAT = 1 THEN 'Cancel'
WHEN ATR_E_FLAT = 0 AND CANCEL_E_FLAT = 0 AND CANCEL_FLAG = 1 THEN 'Cancel'
ELSE 'Pending' END AS STATUS,
COUNT(DISTINCT POL_ID) AS CNT
FROM USER_DB.AD1_PA08042.AUTO_DRIPS
WHERE PYMT_TYPE = 'On Demand' AND BILL_INSTAL_TYP_DESC = 'Monthly Installments'
AND POL_EFF_DT BETWEEN '2024-09-15' AND '2025-03-15' -- Full Roll-Up
AND RISK_ST_ABBR NOT IN ('AZ', 'OH', 'WV') 
GROUP BY CTRL_TEST_CD, BILL_INSTAL_TYP_DESC, STATUS
ORDER BY BILL_INSTAL_TYP_DESC, CTRL_TEST_CD, STATUS;

-- Monthly Non-Lapse
SELECT CTRL_TEST_CD,
BILL_INSTAL_TYP_DESC,
CASE 
WHEN ATR_E_FLAT = 1 AND CANCEL_E_FLAT = 0 THEN 'Active'
WHEN ATR_E_FLAT = 1 AND CANCEL_E_FLAT = 1 THEN 'Cancel'
WHEN ATR_E_FLAT = 0 AND CANCEL_E_FLAT = 0 AND CANCEL_FLAG = 1 THEN 'Cancel'
ELSE 'Pending' END AS STATUS,
COUNT(DISTINCT POL_ID) AS CNT
FROM USER_DB.AD1_PA08042.AUTO_DRIPS
WHERE PYMT_TYPE = 'On Demand' AND BILL_INSTAL_TYP_DESC = 'Monthly Installments'
AND POL_EFF_DT BETWEEN '2024-08-28' AND '2025-02-28' -- Full Roll-Up
AND RISK_ST_ABBR IN ('AZ', 'OH', 'WV') 
GROUP BY CTRL_TEST_CD, BILL_INSTAL_TYP_DESC, STATUS
ORDER BY BILL_INSTAL_TYP_DESC, CTRL_TEST_CD, STATUS;