SELECT *
FROM "DSC_PLBI_DB"."APP_HOME_PRD"."HOME_OPERATIONAL_LOSS"
WHERE POL_ID = '01RBA554314'
LIMIT 1

SELECT DISTINCT POL_ID --915
FROM "USER_DB"."AD1_PA08042"."CHAD_DATA"

DROP TABLE "USER_DB"."AD1_PA08042"."CHAD_DATA"
SELECT POL_ID -- 34
FROM "USER_DB"."AD1_PA08042"."PLIC84_DATA"

DELETE FROM "USER_DB"."AD1_PA08042"."HBIP_DATA"
WHERE POL_ID IN (SELECT POL_ID FROM "USER_DB"."AD1_PA08042"."PLIC84_DATA")

CREATE OR REPLACE TRANSIENT TABLE USER_DB.AD1_PA08042.CHAD_DATA
AS
SELECT DISTINCT POL_ID, 'HBIP' AS SOURCE
FROM "USER_DB"."AD1_PA08042"."HBIP_DATA"

INSERT INTO USER_DB.AD1_PA08042.CHAD_DATA
SELECT POL_ID, 'PLIC' AS SOURCE
FROM "USER_DB"."AD1_PA08042"."PLIC84_DATA"

SELECT * FROM USER_DB.AD1_PA08042.CHAD_DATA

WITH cte AS (
SELECT CHAD.POL_ID, EARNED_MONTH, SOURCE, SUM(DERIV_ADJ_EP_AMT) AS EP, SUM(TOTAL_DERIV_INCUR_CLM_LOSS_AMT) AS LOSSES
FROM USER_DB.AD1_PA08042.CHAD_DATA AS CHAD
LEFT JOIN "DSC_PLBI_DB"."APP_HOME_PRD"."HOME_OPERATIONAL_LOSS" AS HOME_OP_LOSS
ON HOME_OP_LOSS.POL_ID = CHAD.POL_ID
GROUP BY CHAD.POL_ID, EARNED_MONTH, SOURCE
ORDER BY CHAD.POL_ID, EARNED_MONTH, SOURCE
)
SELECT COUNT(DISTINCT POL_ID) FROM cte

SELECT POL_ID--, SOURCE
FROM USER_DB.AD1_PA08042.PLIC84_DATA
WHERE POL_ID NOT IN (SELECT DISTINCT POL_ID FROM "DSC_PLBI_DB"."APP_HOME_PRD"."HOME_OPERATIONAL_LOSS")
ORDER BY POL_ID

SELECT *
FROM "DSC_PLBI_DB"."APP_HOME_PRD"."HOME_OPERATIONAL_LOSS"
WHERE POL_ID = '22RB531523'

SELECT PLIC.POL_ID, HBIP.POL_ID FROM "USER_DB"."AD1_PA08042"."PLIC84_DATA" AS PLIC
JOIN "USER_DB"."AD1_PA08042"."HBIP_DATA" AS HBIP
ON PLIC.POL_ID = HBIP.POL_ID