WITH ins_score AS -- Gets latest month's ins score decile PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'Ins Score Decile',(
    CASE WHEN NEWCO_INS_SCR_CD IN (000,0,999) THEN 'NHNS'
         WHEN NEWCO_INS_SCR_CD <= 386 THEN 'Decile 10 Worst'
         WHEN NEWCO_INS_SCR_CD <= 460 THEN 'Decile 09'
         WHEN NEWCO_INS_SCR_CD <= 539 THEN 'Decile 08'
         WHEN NEWCO_INS_SCR_CD <= 617 THEN 'Decile 07'
         WHEN NEWCO_INS_SCR_CD <= 679 THEN 'Decile 06'
         WHEN NEWCO_INS_SCR_CD <= 724 THEN 'Decile 05'
         WHEN NEWCO_INS_SCR_CD <= 756 THEN 'Decile 04'
         WHEN NEWCO_INS_SCR_CD <= 782 THEN 'Decile 03'
         WHEN NEWCO_INS_SCR_CD <= 809 THEN 'Decile 02'
         WHEN NEWCO_INS_SCR_CD <= 980 THEN 'Decile 01 Best' ELSE 'NHNS' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1' 
    GROUP BY KEY
),

hh_comp AS -- Gets latest month's household comp PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'HH Comp',(
    CASE WHEN HH_COMP = 'SC1D' THEN 'a. single vehicle, 1 driver'
         WHEN HH_COMP = 'MC C=D' THEN 'd. multi vehicle, vehicle = driver'
         WHEN HH_COMP = 'SCMT1D' THEN 'b. single vehicle, more than 1 driver' 
         WHEN HH_COMP = 'MCMCTD' THEN 'c. multi vehicle, vehicle > drivers' 
         WHEN HH_COMP = 'MCMDTC' THEN 'e. multi vehicle, vehicle < drivers' 
         WHEN HH_COMP = '0 CARS' THEN 'f. 0 vehicle' ELSE 'g. other' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1' 
    GROUP BY KEY
),

clean_dirty AS -- Gets latest month's Clean/Dirty PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'CLEAN DIRTY DESC', CLEAN_DIRTY_DESC) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1' 
    GROUP BY KEY
),

max_age AS -- Gets latest month's max age group PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'Max Age Group',(
    CASE WHEN POL_MAX_DRVR_AGE < 50 THEN '50'
         WHEN POL_MAX_DRVR_AGE <= 59 THEN '50-59' 
         WHEN POL_MAX_DRVR_AGE <= 69 THEN '50-69' 
         WHEN POL_MAX_DRVR_AGE <= 79 THEN '70-79' 
         WHEN POL_MAX_DRVR_AGE <= 130 THEN '80+' ELSE 'Unknown' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1' 
    GROUP BY KEY
),

min_age AS -- Gets latest month's min age group PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'Min Age Group',(
    CASE WHEN POL_MIN_DRVR_AGE < 50 THEN '50'
         WHEN POL_MIN_DRVR_AGE <= 59 THEN '50-59' 
         WHEN POL_MIN_DRVR_AGE <= 69 THEN '50-69' 
         WHEN POL_MIN_DRVR_AGE <= 79 THEN '70-79' 
         WHEN POL_MIN_DRVR_AGE <= 130 THEN '80+' ELSE 'Unknown' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1' 
    GROUP BY KEY
),

max_minus_min AS -- Gets latest month's (max-min) age group PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'Max Minus Min Age Group',(
    CASE WHEN (POL_MAX_DRVR_AGE - POL_MIN_DRVR_AGE) = 0 THEN 'a. 0'
         WHEN (POL_MAX_DRVR_AGE - POL_MIN_DRVR_AGE) BETWEEN 1 AND 2 THEN 'b. 1-2'
         WHEN (POL_MAX_DRVR_AGE - POL_MIN_DRVR_AGE) BETWEEN 3 AND 6 THEN 'c. 3-6'
         WHEN (POL_MAX_DRVR_AGE - POL_MIN_DRVR_AGE) BETWEEN 7 AND 20 THEN 'd. 7-20'
         WHEN (POL_MAX_DRVR_AGE - POL_MIN_DRVR_AGE) >= 21 THEN 'e. 21+' ELSE 'f. n/a' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1' 
    GROUP BY KEY
),

pcarr_year_cnt AS -- Gets latest month's pcarr YR PIF count 
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'PCARR YR CNT',(
    CASE WHEN PCARR_YR_CNT = 0.5 THEN 'a 0.5'
         WHEN PCARR_YR_CNT = 1.0 THEN 'b 1' 
         WHEN PCARR_YR_CNT = 2.0 THEN 'c 2' 
         WHEN PCARR_YR_CNT = 3.0 THEN 'd 3' 
         WHEN PCARR_YR_CNT = 4.0 THEN 'e 4' 
         WHEN PCARR_YR_CNT = 5.0 THEN 'f 5+' ELSE 'g Unknown' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1' 
    GROUP BY KEY
),

acct_credit AS -- Gets latest month's acct credit PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'POL ACCT CR IND', ACCT_CR_IND) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1' 
    GROUP BY KEY
),

coverage_pkg AS -- Gets latest month's coverage package PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'POL COV PKG CD',(
    CASE WHEN POL_COV_PKG_CD IS NULL OR POL_COV_PKG_CD = 'NO COV' THEN 'Unknown' 
         ELSE POL_COV_PKG_CD END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1' 
    GROUP BY KEY
),

pcarr AS -- Gets latest month's prior carrier PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'Prior Carrier',(
    CASE WHEN PCARR_DESC IN ('STATE FARM INSURANCE') THEN 'STATE FARM'
         WHEN PCARR_DESC IN ('IMPERIAL FIRE AND CA','SAFE AUTO INS CO','ALLSTATE CTY MUTUAL','ALLSTATE FIRE CAS IN','ALLSTATE INDEMNITY C','ALLSTATE INSURANCE C','ALLSTATE OF NEW JERS','ALLSTATE PROPERTY','ANJP C INS CO','CENTURY NATIONAL INS','CENTURY-NATIONAL INS','DIRECT GENERAL INS','DIRECT GENERAL INSUR','DIRECT INSURANCE CO','DIRECT INSURANCE COM','DIRECT NATIONAL INSU','ENCOM H A INS COMP','ENCOM INDEPENDENT IN','ENCOM INS CO OF NJ','ENCOM P C COMP','ENCOMPASS INDEMNITY','ENCOMPASS INS OF AM','ENCOMPASS INSURANCE','ENCOMPASS P C OF NJ','ESURANCE INS CO','ESURANCE INS CO NJ','ESURANCE PROP CAS','IMPERIAL FIRE CASU','INTEGON CASUALTY INS','INTEGON GENERAL INSU','INTEGON INDEMNITY CO','INTEGON NATIONAL','INTEGON NATIONAL INS','INTEGON PREFERRED IN','MIC GENERAL INSURANC','MS-DIRECT GENERAL IN','NATIONAL FARMERS UNI','NATIONAL GENERAL ASS','NATIONAL GENERAL INS','NATIONAL GENERAL PRE','NEW SOUTH INSURANCE','NORTHBROOK INSURANCE','STANDARD PROPERTY AN') THEN 'ALLSTATE'
         WHEN PCARR_DESC IN ('GEICO ADVANTAGE INS','GEICO CASUALTY COMP','GEICO CHOICE INS CO','GEICO COUNTY MTL','GEICO GENERAL INS CO','GEICO INDEMNITY COMP','GEICO SECURE INS CO','GEICOTXCOUNTYMUTUAL','GOVERNMENT EMP INSCO','SOUTHERN COUNTY') THEN 'GEICO'
         WHEN PCARR_DESC IN ('PROGRESSIVE GROUPS') THEN 'PROGRESSIVE'
         WHEN PCARR_DESC IN ('EMPLOYERS INSURANCE','FIRST NAT INS CO AME','GENERAL INS CO AMER','LIB MUTUAL PERSONAL','LIBERTY COUNTY MUTUA','LIBERTY INSURANCE CO','LIBERTY MUTUAL FIRE','LIBERTY MUTUAL INSUR','LIBERTY MUTUAL MID A','LIBERTY PERSONAL INS','LM GENERAL INSURANCE','LM INSURANCE CORPORA','MERIDIAN SECURITY','MERIDIAN SECURITY IN','MILBANK INSURANCE CO','MONTGOMERY MUTUAL IN','PATRONS MUTUAL INS C','PEERLESS INDEMNITY I','SAFECO INS CO AMER','SAFECO INSUR CO ILL','SAFECO INSUR CO IND','SAFECO INSUR CO ORE','SAFECO LLOYDS INS CO','SAFECO NAT INSUR CO','SAIC OF OHIO','SAIC OF WISCONSIN','STATE AUTO MUTUAL','STATE AUTO P C INS','STATE AUTO PROP C','STATE AUTOMOBILE MUT','THE FIRST LIBERTY IN','THE NETHERLANDS INSU','WAUSAU UNDERWRITERS','AMER ECONOMY INS CO','AMER STATES INSUR CO','AMER STATES PREF INS','AMERICA FIRST INSURA','CONSOLIDATED INSURAN') THEN 'LIBERTY'
         WHEN PCARR_DESC IN ('FID GUAR INS UNDRS','PHOENIX INSURANCE CO','ST PAUL PROTECTIVE I','STANDARD FIRE INS CO','TRAVCO INSURANCE CO','TRAVELERS CAS CONN','TRAVELERS COMMERCIAL','TRAVELERS HOME MAR','TRAVELERS INDEM AMER','TRAVELERS INDEM CONN','TRAVELERS INDEMNITY','TRAVELERS P C INS CO','TRAVELERS P C OF AM','TRAVELERS PERSON SEC','TRAVELERS PERSONAL','AUTO INS CO OF HARTF','CHARTER OAK FIRE INS','FIRST FLORIDIAN A H') THEN 'TRAVELERS'
         WHEN PCARR_DESC in ('AMFAM CONNECT INS', 'AMFAM CONNECT PC', 'AMFAM INS CO', 'AMER FAMILY MUTUAL', 'AMERICAN STD INS OH', 'THE GENERAL AUTOMOBI', 'MIDVALE INDEMNITY',     'AFMICSI', 'AMER STANDARD INS', 'AMERICAN FAM INS OH', 'AMERIPRISE INSURANCE', 'HOMESITE INSURANCE C', 'IDS PROPERTY CASUALT', 'MSAA', 'MSAA INSURANCE CO', 'MSAPIC', 'NGM INSURANCE CO', 'ODIC') THEN 'AMERICAN FAMILY'                                                                                                         
         WHEN PCARR_DESC in ('USAA GENERAL IND CO', 'USAA CASUALTY INS CO', 'USAA', 'GARRISON PROP CAS', 'GAR') THEN 'USAA'
         WHEN PCARR_DESC in ('COLONIAL COUNTY MUT', 'ALLIED PROP CAS', 'ALLIED P C INS CO', 'COLONIAL COUNTY MUT', 'CRESTBROOK INSURANCE', 'DEPOSITORS INS CO', 'NATIONWIDE AG INS CO', 'NATIONWIDE AGRI INS', 'NATIONWIDE GENERAL', 'NATIONWIDE INS CO', 'NATIONWIDE INS OF AM', 'NATIONWIDE MUT FIRE', 'NATIONWIDE MUT INS', 'NATIONWIDE MUTUAL IN', 'VICTORIA FIRE CASU','VICTORIA SPECIALTY I', 'AMCO INSURANCE CO', 'ALLIED P C INS CO', 'HARLEYSVILLEIC', 'HARLEYSVILLEPREFIC', 'NATIONWIDE AFFINITY', 'NATIONWIDE GENERAL', 'NATIONWIDE MUTUAL', 'NATIONWIDE PROP CAS', 'VICTORIA SELECT INSU') THEN 'Nationwide'
         WHEN PCARR_DESC IS NULL  THEN 'NULL'
         WHEN PCARR_DESC IN ('NOT PRESENTLY INSURED', 'UNKNOWN', 'NO PRIOR INSURANCE') THEN PCARR_DESC
         WHEN PCARR_DESC IN ('OTHER-NON STANDARD', 'OTHER - NON STANDARD') THEN 'OTHER - NON STANDARD'
         ELSE 'OTHER' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1' 
    GROUP BY KEY
),

insured_age_seg AS -- Gets latest month's insured age group PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'Insured Age Group',(
    CASE WHEN INSURED_AGE <= 49 THEN 'a. 25-49'
         WHEN INSURED_AGE <= 54 THEN 'b. 50-54'
         WHEN INSURED_AGE <= 59 THEN 'c. 55-59'
         WHEN INSURED_AGE <= 64 THEN 'd. 60-64'
         WHEN INSURED_AGE <= 69 THEN 'e. 65-69'
         WHEN INSURED_AGE <= 74 THEN 'f. 70-74'
         WHEN INSURED_AGE <= 79 THEN 'g. 75-79'
         WHEN INSURED_AGE <= 120 THEN 'h. 80+' ELSE 'i. null' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1' 
    GROUP BY KEY
),

ppv AS -- Gets latest month's PPV PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'POL PPV CNT',(
    CASE WHEN POL_PPV_CNT = 1 THEN 'b 1' 
         WHEN POL_PPV_CNT = 2 THEN 'c 2' 
         WHEN POL_PPV_CNT = 3 THEN 'd 3' 
         WHEN POL_PPV_CNT = 4 THEN 'e 4' 
         WHEN POL_PPV_CNT = 5 THEN 'f 5+' ELSE 'g Unknown' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1'
    GROUP BY KEY
),

young_driver AS -- Gets latest month's young driver ind PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'YOUTH OPER DRVR IND', YOUTH_OPER_DRVR_IND) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1'
    GROUP BY KEY
),

garage AS -- Gets latest month's garage substate PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'GARAGE SUBSTATE',(
    CASE WHEN LEFT(STATE_ABBR,2) = LEFT(GARAGE_SUBSTATE,2) THEN GARAGE_SUBSTATE ELSE 'Out of State Mail' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1' 
    GROUP BY KEY
),

bi_per_person AS -- Gets latest month's bi per person PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'Prior BI Per Person',(
    CASE WHEN PCARR_BI_PERS_LMT_CD < 50 THEN 'a. Less than 50'                                   
         WHEN PCARR_BI_PERS_LMT_CD < 100 THEN 'b. 50-99'                                      
         WHEN PCARR_BI_PERS_LMT_CD < 250 THEN 'c. 100-249'                                    
         WHEN PCARR_BI_PERS_LMT_CD < 3000 THEN 'd. 250+'                                        
         WHEN PCARR_BI_PERS_LMT_CD IS NULL THEN 'f. Unknown/No Insurance' ELSE 'e. other' END)) as Key,                                      
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1' 
    GROUP BY KEY
),

adv_qte_days AS -- Gets latest month's advanced quote days PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'Advanced Quote Discount',(
    CASE WHEN ADV_QTE_DAY_CNT in (000,0,999) THEN 'A. 0 Days'
         WHEN ADV_QTE_DAY_CNT <= 13 THEN 'B. 1-13'
         WHEN ADV_QTE_DAY_CNT <= 60 THEN 'C. 14-60'
         WHEN ADV_QTE_DAY_CNT <= 75 THEN 'D. 61-75'
         WHEN ADV_QTE_DAY_CNT <= 99999 THEN 'E. 76+' ELSE 'F. Unknown' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1'
    GROUP BY KEY
),

min_rating_factor AS -- Gets latest month's min rating factor PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'Min Rating Factor', POL_MIN_RATE_FCTR_IND) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" LEFT JOIN 
    (SELECT AUTO_POL_TRANS_ID, POL_MIN_RATE_FCTR_IND FROM "PRD_PL_DB"."APP_DCPA_AUTO_CURATE"."AUTO_POLICY" GROUP BY AUTO_POL_TRANS_ID, POL_MIN_RATE_FCTR_IND)
    USING (AUTO_POL_TRANS_ID)
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1'
    GROUP BY KEY
),

renew_uw_tier AS -- Gets latest month's UW tier PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'RENEW UW TIER',(
    CASE WHEN RENEW_UW_TIER_CD in ('BB','BC','BD','BE','BF','BG','BH','BI','BJ','BK') THEN RENEW_UW_TIER_CD ELSE 'Other' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1'
    GROUP BY KEY
),

max_veh_age AS -- Gets latest month's max vehicle age PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'Max Veh Age',(
    CASE WHEN POL_MAX_VEH_AGE <= 3 THEN '0-3'
         WHEN POL_MAX_VEH_AGE <= 6 THEN '4-6'
         WHEN POL_MAX_VEH_AGE <= 9 THEN '7-9'
         WHEN POL_MAX_VEH_AGE <= 14 THEN '10-14'
         WHEN POL_MAX_VEH_AGE <= 19 THEN '15-19'
         WHEN POL_MAX_VEH_AGE <= 24 THEN '20-24'
         WHEN POL_MAX_VEH_AGE > 24 THEN '25+' ELSE 'Other' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1'
    GROUP BY KEY
),

single_vehicle AS -- Gets latest month's single vehicle code PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'POL MULTI SNGL VEH CD', POL_MULTI_SNGL_VEH_CD) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" 
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1'
    GROUP BY KEY
),

mature_driving AS -- Gets latest month's mature driving course ind PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'Mature Driving Course', POL_MATUR_DRVNG_COURS_CR_IND) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" LEFT JOIN 
    (SELECT AUTO_POL_TRANS_ID, POL_MATUR_DRVNG_COURS_CR_IND FROM "PRD_PL_DB"."APP_DCPA_AUTO_CURATE"."AUTO_POLICY" GROUP BY AUTO_POL_TRANS_ID, POL_MATUR_DRVNG_COURS_CR_IND)
    USING (AUTO_POL_TRANS_ID)
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1'
    GROUP BY KEY
),

incident_free_yr AS -- Gets latest month's incident free yr PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'Incident Free Year Count', POL_INCID_FREE_YR_CNT) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" LEFT JOIN
    (SELECT AUTO_POL_TRANS_ID, POL_INCID_FREE_YR_CNT FROM "PRD_PL_DB"."APP_DCPA_AUTO_CURATE"."AUTO_POLICY" GROUP BY AUTO_POL_TRANS_ID, POL_INCID_FREE_YR_CNT)
    USING (AUTO_POL_TRANS_ID)
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1'
    GROUP BY KEY
),

naf_acct_count AS -- Gets latest month's NAF accident PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'NAF Accident Count',(
    CASE WHEN POL_TTL_NAF_ACCID_CNT = 0 THEN '0'
         WHEN POL_TTL_NAF_ACCID_CNT = 1 THEN '1'
         WHEN POL_TTL_NAF_ACCID_CNT > 1 THEN '2+' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND"
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1'
    GROUP BY KEY
),

incident_month_age AS -- Gets latest month's incident month age PIF count
(
    SELECT CONCAT(STATE_ABBR, RATE_PLAN_CD, 'Incident Month Age', POL_LATST_INCID_MO_AGE,(
    CASE WHEN POL_LATST_INCID_MO_AGE BETWEEN 1 AND 12 THEN '1-12'
         WHEN POL_LATST_INCID_MO_AGE BETWEEN 13 AND 24 THEN '13-24'
         WHEN POL_LATST_INCID_MO_AGE BETWEEN 25 AND 36 THEN '25-36'
         WHEN POL_LATST_INCID_MO_AGE BETWEEN 37 AND 48 THEN '37-48'
         WHEN POL_LATST_INCID_MO_AGE BETWEEN 49 AND 60 THEN '49-60'
         WHEN POL_LATST_INCID_MO_AGE = 61 THEN '61'
         WHEN POL_LATST_INCID_MO_AGE = 0 THEN '0' END)) as Key,
    COUNT(POLICY_ID) as PIF
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_INFORCE_MONTHEND" t1
    WHERE BUS_UNIT_ABBR = 'AARP' and LATEST_MONTH_IND = 'Y' and RATE_PLAN_CD = 'HDC1'
    GROUP BY KEY
)

SELECT * FROM
(
    SELECT * FROM ins_score         
    UNION ALL 
    SELECT * FROM hh_comp           
    UNION ALL 
    SELECT * FROM clean_dirty       
    UNION ALL
    SELECT * FROM max_age           
    UNION ALL
    SELECT * FROM min_age           
    UNION ALL
    SELECT * FROM max_minus_min     
    UNION ALL
    SELECT * FROM pcarr_year_cnt    
    UNION ALL
    SELECT * FROM acct_credit       
    UNION ALL
    SELECT * FROM coverage_pkg      
    UNION ALL
    SELECT * FROM pcarr             
    UNION ALL
    SELECT * FROM insured_age_seg   
    UNION ALL
    SELECT * FROM ppv               
    UNION ALL
    SELECT * FROM young_driver      
    UNION ALL
    SELECT * FROM garage            
    UNION ALL
    SELECT * FROM bi_per_person     
    UNION ALL
    SELECT * FROM adv_qte_days      
    UNION ALL
    SELECT * FROM min_rating_factor 
    UNION ALL
    SELECT * FROM renew_uw_tier     
    UNION ALL
    SELECT * FROM max_veh_age       
    UNION ALL
    SELECT * FROM single_vehicle    
    UNION ALL
    SELECT * FROM mature_driving    
    UNION ALL
    SELECT * FROM incident_free_yr  
    UNION ALL
    SELECT * FROM naf_acct_count    
    UNION ALL
    SELECT * FROM incident_month_age
)
ORDER BY KEY