CREATE OR REPLACE TEMPORARY TABLE USER_DB.AD1_PA08042.SEGMENTATION AS
SELECT ULM.*,
AVG(EXPECTED_LOSS_RATIO) OVER (PARTITION BY STATE) AS STATE_MEAN,
EXPECTED_LOSS_RATIO / STATE_MEAN AS ELRR
FROM "DSC_PLDS_DB"."APP_AUTOMATA_PRD"."PREVAIL_AUTO_ULM_QUOTE_POL_AGG_NB_QUALITY" AS ULM 
WHERE TRANS_DT BETWEEN '2022-01-01' AND '2024-06-30' 
AND ISSUE_IND = 'Y'
ORDER BY STATE

SELECT 
CASE CF_HOUSEHOLD_COMPOSITION
WHEN 'single_car_one_driver' THEN '1 Car, 1 Driver'
WHEN 'single_car_more_than_one_driver' THEN '1 Car, 2+ Drivers'
WHEN 'multi_car_cars_equals_drivers' THEN 'Multi Car, Cars = Drivers'
WHEN 'multi_car_more_cars_than_drivers' THEN 'Multi Car, Cars > Drivers'
WHEN 'multi_car_more_drivers_than_cars' THEN 'Multi Car, Cars < Drivers'
END AS HH_COMP, 
COUNT(*) AS POL_CNT, AVG(ELRR) AS ULM_ELRR
FROM USER_DB.AD1_PA08042.SEGMENTATION
GROUP BY HH_COMP
ORDER BY POL_CNT DESC

SELECT CASE
WHEN PNI_AGE < 50 THEN '<50'
WHEN PNI_AGE BETWEEN 50 AND 59 THEN '50-59'
WHEN PNI_AGE BETWEEN 60 and 69 THEN '60-69'
WHEN PNI_AGE BETWEEN 70 and 79 THEN '70-79'
ELSE '80+' END AS PNI_AGE_grp,
COUNT(*) AS POL_CNT, AVG(ELRR) AS ULM_ELRR
FROM USER_DB.AD1_PA08042.SEGMENTATION
GROUP BY PNI_AGE_grp
ORDER BY POL_CNT DESC

SELECT 
CASE CF_ACCOUNT_CREDIT
WHEN 'H' THEN 'No'
WHEN 'None' THEN 'No'
ELSE 'Yes' END AS acct_credit,
COUNT(*) AS POL_CNT, AVG(ELRR) AS ULM_ELRR
FROM USER_DB.AD1_PA08042.SEGMENTATION
GROUP BY acct_credit
ORDER BY POL_CNT DESC

SELECT CF_VEH_TELEMATIC_IND,
COUNT(*) AS POL_CNT, AVG(ELRR) AS ULM_ELRR
FROM USER_DB.AD1_PA08042.SEGMENTATION
GROUP BY CF_VEH_TELEMATIC_IND
ORDER BY POL_CNT DESC

SELECT CASE
WHEN CV_ADV_QUOTE_DAYS_NEW < 0 OR CV_ADV_QUOTE_DAYS_NEW > 365 THEN 'exclude'
WHEN CV_ADV_QUOTE_DAYS_NEW = 0 THEN '0'
WHEN CV_ADV_QUOTE_DAYS_NEW BETWEEN 1 AND 13 THEN '1-13'
WHEN CV_ADV_QUOTE_DAYS_NEW BETWEEN 14 AND 60 THEN '14-60'
WHEN CV_ADV_QUOTE_DAYS_NEW BETWEEN 61 AND 75 THEN '61-75'
WHEN CV_ADV_QUOTE_DAYS_NEW BETWEEN 76 AND 365 THEN '76-365'
END AS adv_qte_days,
COUNT(*) AS POL_CNT, AVG(ELRR) AS ULM_ELRR
FROM USER_DB.AD1_PA08042.SEGMENTATION
GROUP BY adv_qte_days
ORDER BY POL_CNT DESC