WITH agg_veh AS
(
    SELECT CV_PLCY_PERIOD_ID AS POL_PRD_ID,
    SUM(VEH_BI_EXPOSURE * VEH_ADJ_BI_PP_PRED) AS BI_LOSS_AMT,
    SUM(VEH_COLL_EXPOSURE * VEH_ADJ_COLL_PP_PRED) AS COLL_LOSS_AMT,
    SUM(VEH_COMP_EXPOSURE * VEH_ADJ_COMP_PP_PRED) AS COMP_LOSS_AMT,
    SUM(VEH_MP_EXPOSURE * VEH_ADJ_MP_PP_PRED) AS MP_LOSS_AMT,
    SUM(VEH_PD_EXPOSURE * VEH_ADJ_PD_PP_PRED) AS PD_LOSS_AMT,
    SUM(VEH_PIP_EXPOSURE * VEH_ADJ_PIP_PP_PRED) AS PIP_LOSS_AMT,
    SUM(VEH_UM_EXPOSURE * VEH_ADJ_UM_PP_PRED) AS UM_LOSS_AMT
    FROM DSC_PLDS_DB.APP_AUTOMATA_PRD.PREVAIL_AUTO_ULM_POL_VEH_AGG_VW
    GROUP BY POL_PRD_ID
),

get_ulm AS
(
    SELECT *, BI_LOSS_AMT + COLL_LOSS_AMT + COMP_LOSS_AMT + 
    MP_LOSS_AMT + PD_LOSS_AMT + PIP_LOSS_AMT + UM_LOSS_AMT AS TTL_LOSS_AMT
    FROM agg_veh
    WHERE POL_PRD_ID IS NOT NULL
),

get_op_loss AS
(
    SELECT POL_PRD_ID,
    MAX(HH_COMP) AS HOUSEHOLD_COMP,
    MAX(PNI_AGE) AS PNI,
    MAX(ADV_QTE_DAY_CNT) AS AQD,
    MAX(PCARR_BI_LMT_CD) AS PCARR_BI,
    MAX(NEWCO_INS_SCR_CD) AS INS_SCR,
    MAX(INS_SCR_DECILE_INFORCE_CW) AS DECILE_GROUP,
    SUM(TTL_EPAPR_AMT) AS EPAPR,
    SUM(TOTAL_EP_AMT) AS EP,
    --SUM(ULM_TTL_LOSS_AMT) AS ULM_LOSSES
    FROM DSC_PLBI_DB.APP_AUTO_PRD.AUTO_OPERATIONAL_LOSS_TS
    WHERE EARNED_MONTH BETWEEN '202201' AND '202412'
    AND NEWCO_IND = 'Y'
    AND POL_PRD_ID IS NOT NULL
    GROUP BY POL_PRD_ID
),

roll_up AS
(
    SELECT GOL.*, GU.TTL_LOSS_AMT AS ULM_LOSSES
    FROM get_op_loss GOL
    JOIN get_ulm GU
    ON TRY_TO_DECIMAL(GOL.POL_PRD_ID) = TRY_TO_DECIMAL(GU.POL_PRD_ID)
    WHERE GOL.POL_PRD_ID IS NOT NULL AND GU.POL_PRD_ID IS NOT NULL
)

SELECT * FROM
(
-- Household Comp
(SELECT CASE WHEN HOUSEHOLD_COMP = 'SC1D' THEN 'a. 1 Car, 1 Driver'
            WHEN HOUSEHOLD_COMP = 'SCMT1D' THEN 'b. 1 Car, 2+ Drivers'
            WHEN HOUSEHOLD_COMP = 'MCMCTD' THEN 'c. Multi Car, Cars > Drivers'
            WHEN HOUSEHOLD_COMP = 'MC C=D' THEN 'd. Multi Car, Car = Driver'
            WHEN HOUSEHOLD_COMP = 'MCMDTC' THEN 'e. Multi Car, Car < Drivers'
            END AS SEGMENT,
(SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR))) / -- Loss Ratio of Segment
(SELECT SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR)) FROM roll_up) AS LRR,
SUM(EPAPR) / (SELECT NULLIFZERO(SUM(EPAPR)) FROM roll_up) * (SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR))) / 
(SELECT SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR)) FROM roll_up) AS PULSE_CHECK, 'Household Comp' AS "Order"
FROM roll_up
WHERE SEGMENT IS NOT NULL
GROUP BY SEGMENT
ORDER BY SEGMENT)

UNION ALL

-- PNI Age Group
(SELECT CASE WHEN PNI < 50 THEN '<50'
            WHEN PNI >= 50 AND PNI < 60 THEN '50-59'
            WHEN PNI >= 60 AND PNI < 70 THEN '60-69'
            WHEN PNI >= 70 AND PNI < 80 THEN '70-79'
            WHEN PNI >= 80 THEN '80+'
            END AS SEGMENT,
(SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR))) / -- Loss Ratio of Segment
(SELECT SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR)) FROM roll_up) AS LRR,
SUM(EPAPR) / (SELECT NULLIFZERO(SUM(EPAPR)) FROM roll_up) * (SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR))) / 
(SELECT SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR)) FROM roll_up) AS PULSE_CHECK, 'PNI Age' AS "Order"
FROM roll_up
WHERE SEGMENT IS NOT NULL
GROUP BY SEGMENT
ORDER BY SEGMENT)

UNION ALL

-- Advanced Quote Day Count
(SELECT CASE WHEN AQD = 0 THEN 'a. 0'
            WHEN AQD BETWEEN 1 AND 13 THEN 'b. 1-13'
            WHEN AQD BETWEEN 14 AND 60 THEN 'c. 14-60'
            WHEN AQD BETWEEN 61 AND 75 THEN 'd. 61-75'
            WHEN AQD BETWEEN 76 AND 365 THEN 'e. 76-365'
            ELSE 'f. exclude' END AS SEGMENT,
(SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR))) / -- Loss Ratio of Segment
(SELECT SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR)) FROM roll_up) AS LRR,
SUM(EPAPR) / (SELECT NULLIFZERO(SUM(EPAPR)) FROM roll_up) * (SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR))) / 
(SELECT SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR)) FROM roll_up) AS PULSE_CHECK, 'Advanced Quote Days' AS "Order"
FROM roll_up
GROUP BY SEGMENT
ORDER BY SEGMENT)

UNION ALL

-- Insurance Score Decile (derived)
(SELECT CASE WHEN INS_SCR BETWEEN 1 AND 523 THEN 'Decile 10'
            WHEN INS_SCR BETWEEN 524 AND 621 THEN 'Decile 09'
            WHEN INS_SCR BETWEEN 622 AND 685 THEN 'Decile 08'
            WHEN INS_SCR BETWEEN 686 AND 724 THEN 'Decile 07'
            WHEN INS_SCR BETWEEN 725 AND 751 THEN 'Decile 06'
            WHEN INS_SCR BETWEEN 752 AND 772 THEN 'Decile 05'
            WHEN INS_SCR BETWEEN 773 AND 791 THEN 'Decile 04'
            WHEN INS_SCR BETWEEN 792 AND 809 THEN 'Decile 03'
            WHEN INS_SCR BETWEEN 810 AND 830 THEN 'Decile 02'
            WHEN INS_SCR BETWEEN 831 AND 997 THEN 'Decile 01'
            ELSE 'NH/NS' END AS SEGMENT,
(SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR))) / -- Loss Ratio of Segment
(SELECT SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR)) FROM roll_up) AS LRR,
SUM(EPAPR) / (SELECT NULLIFZERO(SUM(EPAPR)) FROM roll_up) * (SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR))) / 
(SELECT SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR)) FROM roll_up) AS PULSE_CHECK, 'Insurance Score Deciles' AS "Order"
FROM roll_up
GROUP BY SEGMENT
ORDER BY SEGMENT)

UNION ALL

-- Prior Carrier BI Limit Code
(SELECT CASE WHEN PCARR_BI LIKE 'CSL%' THEN 'CSL'
            WHEN PCARR_BI IN ('30/60', '15/30', '10/20', '20/40', '25/50') THEN '<50/<100'
            WHEN PCARR_BI IN ('100/300', '50/100') THEN PCARR_BI
            WHEN PCARR_BI IN ('500/1000', '250/500', '500/500') THEN '250+/500+'
            ELSE 'null/unk' END AS SEGMENT,
(SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR))) / -- Loss Ratio of Segment
(SELECT SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR)) FROM roll_up) AS LRR,
SUM(EPAPR) / (SELECT NULLIFZERO(SUM(EPAPR)) FROM roll_up) * (SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR))) / 
(SELECT SUM(ULM_LOSSES) / NULLIFZERO(SUM(EPAPR)) FROM roll_up) AS PULSE_CHECK, 'PCarr BI Limit Code' AS "Order"
FROM roll_up
GROUP BY SEGMENT
ORDER BY SEGMENT
))
ORDER BY "Order", SEGMENT;