WITH hail_yeah AS
(
    select *, CASE WHEN
    PRIMARYRATINGSTATE IN ('OK', 'KS', 'TX', 'CO', 'NE', 'SD', 'WY', 'AR', 'MO', 'IA', 'ND', 'MN', 'MS', 'KY', 'NM', 'LA', 'IN', 'TN', 'IL', 'MT') THEN 'Y'
    ELSE 'N' END AS HAIL_IND,
    AVG(EXPECTED_LOSS_RATIO) OVER (PARTITION BY PRIMARYRATINGSTATE) AS STATE_LR,
    EXPECTED_LOSS_RATIO / STATE_LR AS ULM_TEST
    FROM DSC_PLDS_DB.APP_AUTOMATA_PRD.PREVAIL_HOME_ULM_QUOTE_AGG_NB_QUALITY
    where trans_dt between '2022-01-01' and '2024-12-31' and issue_ind = 'Y'
)

SELECT ROOF_COND_DERIV_SCR_NUM, AVG(ULM_TEST) AS ULM_LRR
FROM hail_yeah
WHERE HAIL_IND = 'Y'
GROUP BY ROOF_COND_DERIV_SCR_NUM
ORDER BY ROOF_COND_DERIV_SCR_NUM

WITH hail_nah AS
(
    select *, CASE WHEN
    PRIMARYRATINGSTATE IN ('OK', 'KS', 'TX', 'CO', 'NE', 'SD', 'WY', 'AR', 'MO', 'IA', 'ND', 'MN', 'MS', 'KY', 'NM', 'LA', 'IN', 'TN', 'IL', 'MT') THEN 'Y'
    ELSE 'N' END AS HAIL_IND,
    AVG(EXPECTED_LOSS_RATIO) OVER (PARTITION BY PRIMARYRATINGSTATE) AS STATE_LR,
    EXPECTED_LOSS_RATIO / STATE_LR AS ULM_TEST
    FROM DSC_PLDS_DB.APP_AUTOMATA_PRD.PREVAIL_HOME_ULM_QUOTE_AGG_NB_QUALITY
    where trans_dt between '2022-01-01' and '2024-12-31' and issue_ind = 'Y'
)

SELECT ROOF_COND_DERIV_SCR_NUM, AVG(ULM_TEST) AS ULM_LRR
FROM hail_nah
WHERE HAIL_IND = 'N'
GROUP BY ROOF_COND_DERIV_SCR_NUM
ORDER BY ROOF_COND_DERIV_SCR_NUM