WITH persist_final AS (
    WITH UniquePolicies AS (
        SELECT DISTINCT POL_ID, CTRL_TEST_CD, COUNT(*) AS CNT
        FROM PRD_PL_DB.APP_DCPA_DM.DRIPS_EXTRACT
        WHERE LOI_CD = 'AUTO' AND CTRL_TEST_CD = 'T'
        AND POL_ID NOT IN (SELECT POL_ID FROM PRD_PL_DB.APP_DCPA_DM.DRIPS_EXTRACT WHERE CTRL_TEST_CD = 'C')
        GROUP BY POL_ID, CTRL_TEST_CD
        HAVING CNT = 1 -- only includes Policy IDs that did not have more than 1 different value for CTRL_TEST_CD
    ),
    join_quote AS (
        SELECT UP.POL_ID AS AUTO_POL_ID, AUTO_Q.QCN AS AUTO_QCN
        FROM UniquePolicies UP
        JOIN PRD_PL_DB.APP_DCPA_DM.AUTO_QUOTE_LATST_VW AS AUTO_Q
        ON UP.POL_ID = AUTO_Q.POL_ID
    ),
    crosswalk_join AS (
        SELECT JQ.*, HOME_QCN, AUTO_POL_ID
        FROM join_quote AS JQ
        JOIN DSC_PLBI_DB.APP_AUTO_PRD.PLBI_PARTY_LINKING_VW AS CROSSWALK
        ON JQ.AUTO_QCN = CROSSWALK.AUTO_QCN
    ),
    home_quote AS (
        SELECT CJ.*, HOME_Q.POL_ID AS HOME_POL_ID
        FROM crosswalk_join AS CJ
        JOIN PRD_PL_DB.APP_DCPA_DM.PROP_QUOTE_DWELL_LATST_VW AS HOME_Q
        ON CJ.HOME_QCN = HOME_Q.QCN
        WHERE HOME_POL_ID IS NOT NULL
    )
    
    SELECT HQ.HOME_POL_ID, COMB_PERSIST.*,
    FROM home_quote AS HQ 
    JOIN DSC_PLBI_DB.APP_HOME_PRD.HOME_PERSISTENCY_COMBINED AS COMB_PERSIST
    ON HQ.HOME_POL_ID = COMB_PERSIST.POL_ID
    WHERE COMB_PERSIST.NEWCO_IND = 'Y'
    AND ACCOUNT_CREDIT = 'ACCOUNT'
    QUALIFY MAX(POL_EFF_DT) OVER (PARTITION BY HQ.HOME_POL_ID) = POL_EFF_DT
    ORDER BY HOME_POL_ID

)

SELECT *
-- ((CASE
--   WHEN SUM("ATR_E_FLAT") IS NOT NULL THEN SUM("ATR_E_FLAT")
--   ELSE 0
-- END - CASE
--   WHEN SUM("CANCEL_E_FLAT") IS NOT NULL THEN SUM("CANCEL_E_FLAT")
--   ELSE 0
-- END) / NULLIF(CASE
--   WHEN SUM("ATR_E_FLAT") IS NOT NULL THEN SUM("ATR_E_FLAT")
--   ELSE 0
-- END,0.0)) "E+000 Persistency",
-- ((CASE
--   WHEN SUM("ATR_E_30") IS NOT NULL THEN SUM("ATR_E_30")
--   ELSE 0
-- END - CASE
--   WHEN SUM("CANCEL_E_30") IS NOT NULL THEN SUM("CANCEL_E_30")
--   ELSE 0
-- END) / NULLIF(CASE
--   WHEN SUM("ATR_E_30") IS NOT NULL THEN SUM("ATR_E_30")
--   ELSE 0
-- END,0.0)) "E+030 Persistency",
-- ((CASE
--   WHEN SUM("ATR_E_60") IS NOT NULL THEN SUM("ATR_E_60")
--   ELSE 0
-- END - CASE
--   WHEN SUM("CANCEL_E_60") IS NOT NULL THEN SUM("CANCEL_E_60")
--   ELSE 0
-- END) / NULLIF(CASE
--   WHEN SUM("ATR_E_60") IS NOT NULL THEN SUM("ATR_E_60")
--   ELSE 0
-- END,0.0)) "E+060 Persistency"
FROM persist_final
--WHERE POL_EFF_DT BETWEEN '2024-12-12' AND '2025-01-27'
--WHERE CANC_EFF_DT >= '2024-12-12' OR CANC_EFF_DT IS NULL;