WITH auto_persistency AS
(
    SELECT ap.POL_ID AS AUTO_POL_ID,
    ap.POL_EFF_DT AS AUTO_POL_EFF_DT
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_PERSISTENCY_COMBINED" AS ap
    QUALIFY MAX(ap.POL_EFF_DT) OVER (PARTITION BY ap.POL_ID) = ap.POL_EFF_DT
),

home_persistency AS
(
    SELECT hp.POL_ID AS HOME_POL_ID,
    hp.POL_EFF_DT AS HOME_POL_EFF_DT
    FROM "DSC_PLBI_DB"."APP_HOME_PRD"."HOME_PERSISTENCY_COMBINED" AS hp
    QUALIFY MAX(hp.POL_EFF_DT) OVER (PARTITION BY hp.POL_ID) = hp.POL_EFF_DT
)

SELECT 
ap.*,
AUTO_Q.QCN AS AUTO_QCN,
CROSSWALK.HOME_QCN AS HOME_QCN,
HOME_Q.POL_ID AS HOME_POL_ID,
hp.*
FROM auto_persistency AS ap
JOIN "PRD_PL_DB"."APP_DCPA_DM"."AUTO_QUOTE_LATST_VW" AS AUTO_Q
ON CAST(ap.AUTO_POL_ID AS VARCHAR) = CAST(AUTO_Q.POL_ID AS VARCHAR)
JOIN "DSC_PLBI_DB"."APP_AUTO_PRD"."PLBI_PARTY_LINKING_VW" AS CROSSWALK
ON AUTO_Q.QCN = CROSSWALK.AUTO_QCN
JOIN "PRD_PL_DB"."APP_DCPA_DM"."PROP_QUOTE_DWELL_LATST_VW" AS HOME_Q 
ON CROSSWALK.HOME_QCN = HOME_Q.QCN
JOIN home_persistency AS hp
ON CAST(HOME_Q.POL_ID AS VARCHAR) = CAST(hp.HOME_POL_ID AS VARCHAR)