WITH filtered_char_ref AS
(
    SELECT 
    POLICY_ID,
    POL_PRD_ID,
    POL_EFF_DT,
    ACCOUNT_CREDIT,
    HOME_INSPCT_COMPL_IND,
    RISK_STATE,
    FROM DSC_PLBI_DB.APP_HOME_PRD.HOME_POLICY_CHAR_REF 
    WHERE POL_EFF_DT >= 20200101
),

rolled_up AS
(
    SELECT POL_ID AS POLICY_ID,
    POL_PRD_ID,
    SUM(TOTAL_EE_AMT) AS EE,
    SUM(TOTAL_INCUR_LOSS_AMT) AS INCUR_LOSS,
    SUM(TOTAL_ULT_LOSS_AMT_BF) AS ULT_LOSS,
    SUM(TOTAL_EP_AMT) AS EP_AMT
    FROM DSC_PLBI_DB.APP_HOME_PRD.HOME_OPERATIONAL_LOSS_TS
    WHERE NEWCO_IND = 'N'
    GROUP BY POLICY_ID, POL_PRD_ID
),

joined AS
(
    SELECT *
    FROM filtered_char_ref AS CR
    JOIN rolled_up AS RU
    USING (POLICY_ID, POL_PRD_ID)
),

agged_metrics AS
(
    SELECT SUM(INCUR_LOSS) / SUM(EP_AMT) AS total_loss_ratio,
    SUM(EE) AS EARNED_E
    FROM joined 
    WHERE POL_EFF_DT >= 20200101
)

SELECT ACCOUNT_CREDIT, HOME_INSPCT_COMPL_IND,
SUM(EE) AS EARNED_EXPOSURE,
CONCAT(ROUND(SUM(ULT_LOSS) / SUM(EP_AMT) * 100,  1), '%') AS ULT_LOSS_RATIO,
CONCAT(ROUND(SUM(INCUR_LOSS) / SUM(EP_AMT) * 100, 1), '%') AS INCUR_LOSS_RATIO,
CONCAT(ROUND(SUM(EE) / (SELECT EARNED_E FROM agged_metrics) * 100, 1), '%') AS EE_PERCENT,
SUM(ULT_LOSS) AS ULTIMATE_LOSS,
SUM(INCUR_LOSS) AS INCURRED_LOSS,
SUM(EP_AMT) AS EP,
FROM joined
GROUP BY ACCOUNT_CREDIT, HOME_INSPCT_COMPL_IND
ORDER BY ACCOUNT_CREDIT, HOME_INSPCT_COMPL_IND

/*
SELECT ACCOUNT_CREDIT, HOME_INSPCT_COMPL_IND,
SUM(EP_AMT) AS SEGMENT_EP,
ROUND((SUM(INCUR_LOSS) / SUM(EP_AMT)) / 
(SUM(SUM(INCUR_LOSS)) OVER (PARTITION BY ACCOUNT_CREDIT) / SUM(SUM(EP_AMT)) OVER (PARTITION BY ACCOUNT_CREDIT)), 2) AS LRR
FROM joined
WHERE POL_EFF_DT >= 20200101
GROUP BY ACCOUNT_CREDIT, HOME_INSPCT_COMPL_IND
ORDER BY ACCOUNT_CREDIT, HOME_INSPCT_COMPL_IND
*/

/*
SELECT ACCOUNT_CREDIT,
SUM(EP_AMT) AS SEGMENT_EP,
ROUND((SUM(INCUR_LOSS) / SUM(EP_AMT)) / 
(SELECT total_loss_ratio FROM agged_metrics), 2) AS LRR
FROM joined
WHERE POL_EFF_DT >= 20200101
GROUP BY ACCOUNT_CREDIT
ORDER BY ACCOUNT_CREDIT
*/