SELECT POLICY_ID, TO_DATE(CAST(POL_EFF_DT AS VARCHAR),'YYYYMMDD') AS POL_EFF_DT,
STATE_ABBR, ACCT_CR_IND, HH_COMP, INS_SCORE_GRP, INSURED_AGE, 
POL_NEW_RNW_CD, RATE_PLAN_CD, INS_SCORE_CD, YEARS_WITH_HIG, 
CLEAN_DIRTY, POL_LATST_INCID_MO_AGE_GRP, FLAT_CANCEL_FLAG, PREV_TERM_LATEST_PREMIUM,
-- Case Statements
CASE WHEN CASE WHEN sum(FRST_TRANS_PREM) IS NOT NULL THEN sum(FRST_TRANS_PREM) ELSE 0 END = 0 THEN NULL
       ELSE ((CASE WHEN sum(CASE WHEN (LOWER(POL_NEW_RNW_CD) <> 'n'
          AND CASE
            WHEN PREV_TERM_LATEST_PREMIUM IS NOT NULL THEN PREV_TERM_LATEST_PREMIUM
            ELSE 0
          END <> 0
        ) THEN FRST_TRANS_PREM
        ELSE NULL
      END) IS NOT NULL THEN sum(CASE
        WHEN (
          LOWER(POL_NEW_RNW_CD) <> 'n'
          AND CASE
            WHEN PREV_TERM_LATEST_PREMIUM IS NOT NULL THEN PREV_TERM_LATEST_PREMIUM
            ELSE 0
          END <> 0
        ) THEN FRST_TRANS_PREM
        ELSE NULL
      END)
      ELSE 0
    END / NULLIF(CASE
      WHEN sum(CASE
        WHEN (
          LOWER(POL_NEW_RNW_CD) <> 'n'
          AND CASE
            WHEN PREV_TERM_LATEST_PREMIUM IS NOT NULL THEN PREV_TERM_LATEST_PREMIUM
            ELSE 0
          END <> 0
        ) THEN PREV_TERM_LATEST_PREMIUM
        ELSE NULL
      END) IS NOT NULL THEN sum(CASE
        WHEN (
          LOWER(POL_NEW_RNW_CD) <> 'n'
          AND CASE
            WHEN PREV_TERM_LATEST_PREMIUM IS NOT NULL THEN PREV_TERM_LATEST_PREMIUM
            ELSE 0
          END <> 0
        ) THEN PREV_TERM_LATEST_PREMIUM
        ELSE NULL
      END)
      ELSE 0
    END,0.0)) - 1) END AS OFFERED_PREMIUM_CHANGE
FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_PERSISTENCY_NOWCO"
WHERE TO_DATE(CAST(POL_EFF_DT AS varchar),'yyyymmdd') BETWEEN '2025-05-19' AND '2025-05-25'
AND LOWER(POL_NEW_RNW_CD) = 'r'
AND PREV_TERM_LATEST_PREMIUM >= 300 -- Added per Karissa's request
AND (STATE_ABBR IS NULL OR LOWER(STATE_ABBR) IN (
      'ak', 'al', 'ar', 'az', 'co', 'ct', 'dc', 'de', 'fl', 'ga', 'ia', 'id', 'il', 
      'in', 'ks', 'ky', 'la', 'md', 'me', 'mi', 'mn', 'mo', 'ms', 'mt', 'nd', 'ne', 
      'nh', 'nj', 'nm', 'oh', 'ok', 'or', 'pa', 'ri', 'sc', 'sd', 'tn', 'tx', 'ut', 
      'va', 'vt', 'wi', 'wv', 'wy'))
AND (POL_LATST_INCID_MO_AGE_GRP IS NULL OR LOWER(POL_LATST_INCID_MO_AGE_GRP) IN ('0', '13-24', '25-36', '37', '38-60', '61'))
AND FLAT_CANCEL_FLAG = 0
GROUP BY POLICY_ID, POL_EFF_DT, STATE_ABBR, ACCT_CR_IND, 
HH_COMP, INS_SCORE_GRP, INSURED_AGE, POL_NEW_RNW_CD, RATE_PLAN_CD, 
INS_SCORE_CD, YEARS_WITH_HIG, CLEAN_DIRTY, POL_LATST_INCID_MO_AGE_GRP, FLAT_CANCEL_FLAG, PREV_TERM_LATEST_PREMIUM
HAVING OFFERED_PREMIUM_CHANGE >= 0.4
ORDER BY POL_EFF_DT;