/* Adds Home identifier and rank number to each Persistency row */
WITH labeled_hp AS 
(
SELECT 'Home' AS POL_TYPE,
ROW_NUMBER() OVER (PARTITION BY POL_ID ORDER BY POL_EFF_DT DESC) AS home_rn,
* FROM "DSC_PLBI_DB"."APP_HOME_PRD"."HOME_PERSISTENCY_COMBINED"
),

/* Only takes the most recent row for each unique policy ID */
filtered_hp AS
(
SELECT * FROM labeled_hp WHERE home_rn = 1
),

/* Adds Auto identifier and rank number to each Persistency row */
labeled_ap AS 
(
SELECT 'Auto' AS POL_TYPE, 
ROW_NUMBER() OVER (PARTITION BY POL_ID ORDER BY POL_EFF_DT DESC) AS auto_rn,
* FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_PERSISTENCY_COMBINED"
),

/* Only takes the most recent row for each unique policy ID */
filtered_ap AS 
(
SELECT * FROM labeled_ap WHERE auto_rn = 1
),

filtered_rz AS
(
SELECT POL_ID, MAX(EVENT_DAY) AS EVENT_DAY
FROM USER_DB.AD1_PA08042.RENEWAL_ZONE
GROUP BY POL_ID
),

combined AS
(
SELECT RZ.*,
/* Each Coalesce statement is stacking home and auto values on top of each other
This way, they can be in the same dataset */
COALESCE(AP.POL_TYPE, HP.POL_TYPE) AS POL_TYPE,
COALESCE(AP.POL_EFF_DT, HP.POL_EFF_DT) AS POL_EFF_DT,
COALESCE(AP.ATR_E_FLAT, HP.ATR_E_FLAT) AS ATR_E_FLAT,
COALESCE(AP.ATR_E_30, HP.ATR_E_30) AS ATR_E_30,
COALESCE(AP.ATR_E_60, HP.ATR_E_60) AS ATR_E_60,
COALESCE(AP.ATR_E_90, HP.ATR_E_90) AS ATR_E_90,
COALESCE(AP.ATR_E_120, HP.ATR_E_120) AS ATR_E_120,
COALESCE(AP.ATR_E_150, HP.ATR_E_150) AS ATR_E_150,
COALESCE(AP.ATR_E_185, HP.ATR_E_180) AS ATR_E_185_HOME_180,
COALESCE(NULL, HP.ATR_E_210) AS ATR_E_210,
COALESCE(NULL, HP.ATR_E_240) AS ATR_E_240,
COALESCE(NULL, HP.ATR_E_270) AS ATR_E_270,
COALESCE(NULL, HP.ATR_E_300) AS ATR_E_300,
COALESCE(NULL, HP.ATR_E_330) AS ATR_E_330,
COALESCE(NULL, HP.ATR_E_365) AS ATR_E_365,
COALESCE(AP.CANCEL_FLAG, HP.CANCEL_FLAG) AS CANCEL_FLAG,
COALESCE(AP.CANCEL_E_FLAT, HP.CANCEL_E_FLAT) AS CANCEL_E_FLAT,
COALESCE(AP.CANCEL_E_30, HP.CANCEL_E_30) AS CANCEL_E_30,
COALESCE(AP.CANCEL_E_90, HP.CANCEL_E_90) AS CANCEL_E_90,
COALESCE(AP.CANCEL_E_120, HP.CANCEL_E_120) AS CANCEL_E_120,
COALESCE(AP.CANCEL_E_150, HP.CANCEL_E_150) AS CANCEL_E_150,
COALESCE(AP.CANCEL_E_185, HP.CANCEL_E_180) AS CANCEL_E_185_HOME_180,
COALESCE(NULL, HP.CANCEL_E_210) AS CANCEL_E_210,
COALESCE(NULL, HP.CANCEL_E_240) AS CANCEL_E_240,
COALESCE(NULL, HP.CANCEL_E_270) AS CANCEL_E_270,
COALESCE(NULL, HP.CANCEL_E_300) AS CANCEL_E_300,
COALESCE(NULL, HP.CANCEL_E_330) AS CANCEL_E_330,
COALESCE(NULL, HP.CANCEL_E_365) AS CANCEL_E_365
FROM filtered_rz AS RZ
/* Joins home and auto persistency to Caitlin's cleaned dataset */
LEFT JOIN filtered_ap AS AP
ON CAST(RZ.POL_ID AS VARCHAR) = CAST(AP.POL_ID AS VARCHAR)
LEFT JOIN filtered_hp AS HP
ON CAST(RZ.POL_ID AS VARCHAR) = CAST(HP.POL_ID AS VARCHAR)
)

SELECT *
FROM combined
WHERE POL_TYPE = 'Auto'