WITH state_lob AS 
(
    SELECT CONCAT(RISK_ST_ABBR, LOB) as Key,
    -- Response
    ind_funnel_scorecard(1, QUOTE_DT, RESPONSE_IND) AS "01 RESPONSE",
    ind_funnel_scorecard(2, QUOTE_DT, RESPONSE_IND) AS "02 RESPONSE",
    ind_funnel_scorecard(3, QUOTE_DT, RESPONSE_IND) AS "03 RESPONSE",
    ind_funnel_scorecard(4, QUOTE_DT, RESPONSE_IND) AS "04 RESPONSE",
    ind_funnel_scorecard(5, QUOTE_DT, RESPONSE_IND) AS "05 RESPONSE",
    ind_funnel_scorecard(6, QUOTE_DT, RESPONSE_IND) AS "06 RESPONSE",
    ind_funnel_scorecard(7, QUOTE_DT, RESPONSE_IND) AS "07 RESPONSE",
    ind_funnel_scorecard(8, QUOTE_DT, RESPONSE_IND) AS "08 RESPONSE",
    ind_funnel_scorecard(9, QUOTE_DT, RESPONSE_IND) AS "09 RESPONSE",
    ind_funnel_scorecard(10, QUOTE_DT, RESPONSE_IND) AS "10 RESPONSE",
    ind_funnel_scorecard(11, QUOTE_DT, RESPONSE_IND) AS "11 RESPONSE",
    ind_funnel_scorecard(12, QUOTE_DT, RESPONSE_IND) AS "12 RESPONSE",
    ind_funnel_scorecard(13, QUOTE_DT, RESPONSE_IND) AS "13 RESPONSE",
    ind_funnel_scorecard(14, QUOTE_DT, RESPONSE_IND) AS "14 RESPONSE",
    ind_funnel_scorecard(15, QUOTE_DT, RESPONSE_IND) AS "15 RESPONSE",
    ind_funnel_scorecard(16, QUOTE_DT, RESPONSE_IND) AS "16 RESPONSE",
    ind_funnel_scorecard(17, QUOTE_DT, RESPONSE_IND) AS "17 RESPONSE",
    ind_funnel_scorecard(18, QUOTE_DT, RESPONSE_IND) AS "18 RESPONSE",
    ind_funnel_scorecard(19, QUOTE_DT, RESPONSE_IND) AS "19 RESPONSE",
    -- Success
    ind_funnel_scorecard(1, QUOTE_DT, SUCCESS_IND) AS "01 SUCCESS",
    ind_funnel_scorecard(2, QUOTE_DT, SUCCESS_IND) AS "02 SUCCESS",
    ind_funnel_scorecard(3, QUOTE_DT, SUCCESS_IND) AS "03 SUCCESS",
    ind_funnel_scorecard(4, QUOTE_DT, SUCCESS_IND) AS "04 SUCCESS",
    ind_funnel_scorecard(5, QUOTE_DT, SUCCESS_IND) AS "05 SUCCESS",
    ind_funnel_scorecard(6, QUOTE_DT, SUCCESS_IND) AS "06 SUCCESS",
    ind_funnel_scorecard(7, QUOTE_DT, SUCCESS_IND) AS "07 SUCCESS",
    ind_funnel_scorecard(8, QUOTE_DT, SUCCESS_IND) AS "08 SUCCESS",
    ind_funnel_scorecard(9, QUOTE_DT, SUCCESS_IND) AS "09 SUCCESS",
    ind_funnel_scorecard(10, QUOTE_DT, SUCCESS_IND) AS "10 SUCCESS",
    ind_funnel_scorecard(11, QUOTE_DT, SUCCESS_IND) AS "11 SUCCESS",
    ind_funnel_scorecard(12, QUOTE_DT, SUCCESS_IND) AS "12 SUCCESS",
    ind_funnel_scorecard(13, QUOTE_DT, SUCCESS_IND) AS "13 SUCCESS",
    ind_funnel_scorecard(14, QUOTE_DT, SUCCESS_IND) AS "14 SUCCESS",
    ind_funnel_scorecard(15, QUOTE_DT, SUCCESS_IND) AS "15 SUCCESS",
    ind_funnel_scorecard(16, QUOTE_DT, SUCCESS_IND) AS "16 SUCCESS",
    ind_funnel_scorecard(17, QUOTE_DT, SUCCESS_IND) AS "17 SUCCESS",
    ind_funnel_scorecard(18, QUOTE_DT, SUCCESS_IND) AS "18 SUCCESS",
    ind_funnel_scorecard(19, QUOTE_DT, SUCCESS_IND) AS "19 SUCCESS",
    -- Competitive
    ind_funnel_scorecard(1, QUOTE_DT, COMPETITIVE_IND) AS "01 COMPETITIVE",
    ind_funnel_scorecard(2, QUOTE_DT, COMPETITIVE_IND) AS "02 COMPETITIVE",
    ind_funnel_scorecard(3, QUOTE_DT, COMPETITIVE_IND) AS "03 COMPETITIVE",
    ind_funnel_scorecard(4, QUOTE_DT, COMPETITIVE_IND) AS "04 COMPETITIVE",
    ind_funnel_scorecard(5, QUOTE_DT, COMPETITIVE_IND) AS "05 COMPETITIVE",
    ind_funnel_scorecard(6, QUOTE_DT, COMPETITIVE_IND) AS "06 COMPETITIVE",
    ind_funnel_scorecard(7, QUOTE_DT, COMPETITIVE_IND) AS "07 COMPETITIVE",
    ind_funnel_scorecard(8, QUOTE_DT, COMPETITIVE_IND) AS "08 COMPETITIVE",
    ind_funnel_scorecard(9, QUOTE_DT, COMPETITIVE_IND) AS "09 COMPETITIVE",
    ind_funnel_scorecard(10, QUOTE_DT, COMPETITIVE_IND) AS "10 COMPETITIVE",
    ind_funnel_scorecard(11, QUOTE_DT, COMPETITIVE_IND) AS "11 COMPETITIVE",
    ind_funnel_scorecard(12, QUOTE_DT, COMPETITIVE_IND) AS "12 COMPETITIVE",
    ind_funnel_scorecard(13, QUOTE_DT, COMPETITIVE_IND) AS "13 COMPETITIVE",
    ind_funnel_scorecard(14, QUOTE_DT, COMPETITIVE_IND) AS "14 COMPETITIVE",
    ind_funnel_scorecard(15, QUOTE_DT, COMPETITIVE_IND) AS "15 COMPETITIVE",
    ind_funnel_scorecard(16, QUOTE_DT, COMPETITIVE_IND) AS "16 COMPETITIVE",
    ind_funnel_scorecard(17, QUOTE_DT, COMPETITIVE_IND) AS "17 COMPETITIVE",
    ind_funnel_scorecard(18, QUOTE_DT, COMPETITIVE_IND) AS "18 COMPETITIVE",
    ind_funnel_scorecard(19, QUOTE_DT, COMPETITIVE_IND) AS "19 COMPETITIVE",
    -- Win
    ind_funnel_scorecard(1, QUOTE_DT, WIN_IND) AS "01 WIN",
    ind_funnel_scorecard(2, QUOTE_DT, WIN_IND) AS "02 WIN",
    ind_funnel_scorecard(3, QUOTE_DT, WIN_IND) AS "03 WIN",
    ind_funnel_scorecard(4, QUOTE_DT, WIN_IND) AS "04 WIN",
    ind_funnel_scorecard(5, QUOTE_DT, WIN_IND) AS "05 WIN",
    ind_funnel_scorecard(6, QUOTE_DT, WIN_IND) AS "06 WIN",
    ind_funnel_scorecard(7, QUOTE_DT, WIN_IND) AS "07 WIN",
    ind_funnel_scorecard(8, QUOTE_DT, WIN_IND) AS "08 WIN",
    ind_funnel_scorecard(9, QUOTE_DT, WIN_IND) AS "09 WIN",
    ind_funnel_scorecard(10, QUOTE_DT, WIN_IND) AS "10 WIN",
    ind_funnel_scorecard(11, QUOTE_DT, WIN_IND) AS "11 WIN",
    ind_funnel_scorecard(12, QUOTE_DT, WIN_IND) AS "12 WIN",
    ind_funnel_scorecard(13, QUOTE_DT, WIN_IND) AS "13 WIN",
    ind_funnel_scorecard(14, QUOTE_DT, WIN_IND) AS "14 WIN",
    ind_funnel_scorecard(15, QUOTE_DT, WIN_IND) AS "15 WIN",
    ind_funnel_scorecard(16, QUOTE_DT, WIN_IND) AS "16 WIN",
    ind_funnel_scorecard(17, QUOTE_DT, WIN_IND) AS "17 WIN",
    ind_funnel_scorecard(18, QUOTE_DT, WIN_IND) AS "18 WIN",
    ind_funnel_scorecard(19, QUOTE_DT, WIN_IND) AS "19 WIN",
    -- Bridged
    ind_funnel_scorecard(1, QUOTE_DT, BRIDGED_IND) AS "01 BRIDGED",
    ind_funnel_scorecard(2, QUOTE_DT, BRIDGED_IND) AS "02 BRIDGED",
    ind_funnel_scorecard(3, QUOTE_DT, BRIDGED_IND) AS "03 BRIDGED",
    ind_funnel_scorecard(4, QUOTE_DT, BRIDGED_IND) AS "04 BRIDGED",
    ind_funnel_scorecard(5, QUOTE_DT, BRIDGED_IND) AS "05 BRIDGED",
    ind_funnel_scorecard(6, QUOTE_DT, BRIDGED_IND) AS "06 BRIDGED",
    ind_funnel_scorecard(7, QUOTE_DT, BRIDGED_IND) AS "07 BRIDGED",
    ind_funnel_scorecard(8, QUOTE_DT, BRIDGED_IND) AS "08 BRIDGED",
    ind_funnel_scorecard(9, QUOTE_DT, BRIDGED_IND) AS "09 BRIDGED",
    ind_funnel_scorecard(10, QUOTE_DT, BRIDGED_IND) AS "10 BRIDGED",
    ind_funnel_scorecard(11, QUOTE_DT, BRIDGED_IND) AS "11 BRIDGED",
    ind_funnel_scorecard(12, QUOTE_DT, BRIDGED_IND) AS "12 BRIDGED",
    ind_funnel_scorecard(13, QUOTE_DT, BRIDGED_IND) AS "13 BRIDGED",
    ind_funnel_scorecard(14, QUOTE_DT, BRIDGED_IND) AS "14 BRIDGED",
    ind_funnel_scorecard(15, QUOTE_DT, BRIDGED_IND) AS "15 BRIDGED",
    ind_funnel_scorecard(16, QUOTE_DT, BRIDGED_IND) AS "16 BRIDGED",
    ind_funnel_scorecard(17, QUOTE_DT, BRIDGED_IND) AS "17 BRIDGED",
    ind_funnel_scorecard(18, QUOTE_DT, BRIDGED_IND) AS "18 BRIDGED",
    ind_funnel_scorecard(19, QUOTE_DT, BRIDGED_IND) AS "19 BRIDGED",
    -- Completed Quote
    ind_funnel_scorecard(1, QUOTE_DT, COMPL_QUOTE_IND) AS "01 COMPL_QUOTE",
    ind_funnel_scorecard(2, QUOTE_DT, COMPL_QUOTE_IND) AS "02 COMPL_QUOTE",
    ind_funnel_scorecard(3, QUOTE_DT, COMPL_QUOTE_IND) AS "03 COMPL_QUOTE",
    ind_funnel_scorecard(4, QUOTE_DT, COMPL_QUOTE_IND) AS "04 COMPL_QUOTE",
    ind_funnel_scorecard(5, QUOTE_DT, COMPL_QUOTE_IND) AS "05 COMPL_QUOTE",
    ind_funnel_scorecard(6, QUOTE_DT, COMPL_QUOTE_IND) AS "06 COMPL_QUOTE",
    ind_funnel_scorecard(7, QUOTE_DT, COMPL_QUOTE_IND) AS "07 COMPL_QUOTE",
    ind_funnel_scorecard(8, QUOTE_DT, COMPL_QUOTE_IND) AS "08 COMPL_QUOTE",
    ind_funnel_scorecard(9, QUOTE_DT, COMPL_QUOTE_IND) AS "09 COMPL_QUOTE",
    ind_funnel_scorecard(10, QUOTE_DT, COMPL_QUOTE_IND) AS "10 COMPL_QUOTE",
    ind_funnel_scorecard(11, QUOTE_DT, COMPL_QUOTE_IND) AS "11 COMPL_QUOTE",
    ind_funnel_scorecard(12, QUOTE_DT, COMPL_QUOTE_IND) AS "12 COMPL_QUOTE",
    ind_funnel_scorecard(13, QUOTE_DT, COMPL_QUOTE_IND) AS "13 COMPL_QUOTE",
    ind_funnel_scorecard(14, QUOTE_DT, COMPL_QUOTE_IND) AS "14 COMPL_QUOTE",
    ind_funnel_scorecard(15, QUOTE_DT, COMPL_QUOTE_IND) AS "15 COMPL_QUOTE",
    ind_funnel_scorecard(16, QUOTE_DT, COMPL_QUOTE_IND) AS "16 COMPL_QUOTE",
    ind_funnel_scorecard(17, QUOTE_DT, COMPL_QUOTE_IND) AS "17 COMPL_QUOTE",
    ind_funnel_scorecard(18, QUOTE_DT, COMPL_QUOTE_IND) AS "18 COMPL_QUOTE",
    ind_funnel_scorecard(19, QUOTE_DT, COMPL_QUOTE_IND) AS "19 COMPL_QUOTE",
    -- Issue
    ind_funnel_scorecard(1, QUOTE_DT, ISSUE_IND) AS "01 ISSUE",
    ind_funnel_scorecard(2, QUOTE_DT, ISSUE_IND) AS "02 ISSUE",
    ind_funnel_scorecard(3, QUOTE_DT, ISSUE_IND) AS "03 ISSUE",
    ind_funnel_scorecard(4, QUOTE_DT, ISSUE_IND) AS "04 ISSUE",
    ind_funnel_scorecard(5, QUOTE_DT, ISSUE_IND) AS "05 ISSUE",
    ind_funnel_scorecard(6, QUOTE_DT, ISSUE_IND) AS "06 ISSUE",
    ind_funnel_scorecard(7, QUOTE_DT, ISSUE_IND) AS "07 ISSUE",
    ind_funnel_scorecard(8, QUOTE_DT, ISSUE_IND) AS "08 ISSUE",
    ind_funnel_scorecard(9, QUOTE_DT, ISSUE_IND) AS "09 ISSUE",
    ind_funnel_scorecard(10, QUOTE_DT, ISSUE_IND) AS "10 ISSUE",
    ind_funnel_scorecard(11, QUOTE_DT, ISSUE_IND) AS "11 ISSUE",
    ind_funnel_scorecard(12, QUOTE_DT, ISSUE_IND) AS "12 ISSUE",
    ind_funnel_scorecard(13, QUOTE_DT, ISSUE_IND) AS "13 ISSUE",
    ind_funnel_scorecard(14, QUOTE_DT, ISSUE_IND) AS "14 ISSUE",
    ind_funnel_scorecard(15, QUOTE_DT, ISSUE_IND) AS "15 ISSUE",
    ind_funnel_scorecard(16, QUOTE_DT, ISSUE_IND) AS "16 ISSUE",
    ind_funnel_scorecard(17, QUOTE_DT, ISSUE_IND) AS "17 ISSUE",
    ind_funnel_scorecard(18, QUOTE_DT, ISSUE_IND) AS "18 ISSUE",
    ind_funnel_scorecard(19, QUOTE_DT, ISSUE_IND) AS "19 ISSUE",
    -- HIGAVG
    AVG(div_ind_funnel_scorecard(1, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "01 HIGAVG",
    AVG(div_ind_funnel_scorecard(2, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "02 HIGAVG",
    AVG(div_ind_funnel_scorecard(3, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "03 HIGAVG",
    AVG(div_ind_funnel_scorecard(4, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "04 HIGAVG",
    AVG(div_ind_funnel_scorecard(5, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "05 HIGAVG",
    AVG(div_ind_funnel_scorecard(6, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "06 HIGAVG",
    AVG(div_ind_funnel_scorecard(7, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "07 HIGAVG",
    AVG(div_ind_funnel_scorecard(8, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "08 HIGAVG",
    AVG(div_ind_funnel_scorecard(9, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "09 HIGAVG",
    AVG(div_ind_funnel_scorecard(10, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "10 HIGAVG",
    AVG(div_ind_funnel_scorecard(11, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "11 HIGAVG",
    AVG(div_ind_funnel_scorecard(12, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "12 HIGAVG",
    AVG(div_ind_funnel_scorecard(13, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "13 HIGAVG",
    AVG(div_ind_funnel_scorecard(14, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "14 HIGAVG",
    AVG(div_ind_funnel_scorecard(15, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "15 HIGAVG",
    AVG(div_ind_funnel_scorecard(16, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "16 HIGAVG",
    AVG(div_ind_funnel_scorecard(17, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "17 HIGAVG",
    AVG(div_ind_funnel_scorecard(18, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "18 HIGAVG",
    AVG(div_ind_funnel_scorecard(19, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "19 HIGAVG",
    TO_CHAR(SYSDATE(),'MM-DD-YYYY') AS AS_OF
    FROM "DSC_PLBI_DB"."APP_AGCY_PRD"."AGCY_COMP_RATER_FUNNEL_VW"
    GROUP BY KEY 
),

cw_lob AS
(
    SELECT CONCAT('CW', LOB) as Key,
    -- Response
    ind_funnel_scorecard(1, QUOTE_DT, RESPONSE_IND) AS "01 RESPONSE",
    ind_funnel_scorecard(2, QUOTE_DT, RESPONSE_IND) AS "02 RESPONSE",
    ind_funnel_scorecard(3, QUOTE_DT, RESPONSE_IND) AS "03 RESPONSE",
    ind_funnel_scorecard(4, QUOTE_DT, RESPONSE_IND) AS "04 RESPONSE",
    ind_funnel_scorecard(5, QUOTE_DT, RESPONSE_IND) AS "05 RESPONSE",
    ind_funnel_scorecard(6, QUOTE_DT, RESPONSE_IND) AS "06 RESPONSE",
    ind_funnel_scorecard(7, QUOTE_DT, RESPONSE_IND) AS "07 RESPONSE",
    ind_funnel_scorecard(8, QUOTE_DT, RESPONSE_IND) AS "08 RESPONSE",
    ind_funnel_scorecard(9, QUOTE_DT, RESPONSE_IND) AS "09 RESPONSE",
    ind_funnel_scorecard(10, QUOTE_DT, RESPONSE_IND) AS "10 RESPONSE",
    ind_funnel_scorecard(11, QUOTE_DT, RESPONSE_IND) AS "11 RESPONSE",
    ind_funnel_scorecard(12, QUOTE_DT, RESPONSE_IND) AS "12 RESPONSE",
    ind_funnel_scorecard(13, QUOTE_DT, RESPONSE_IND) AS "13 RESPONSE",
    ind_funnel_scorecard(14, QUOTE_DT, RESPONSE_IND) AS "14 RESPONSE",
    ind_funnel_scorecard(15, QUOTE_DT, RESPONSE_IND) AS "15 RESPONSE",
    ind_funnel_scorecard(16, QUOTE_DT, RESPONSE_IND) AS "16 RESPONSE",
    ind_funnel_scorecard(17, QUOTE_DT, RESPONSE_IND) AS "17 RESPONSE",
    ind_funnel_scorecard(18, QUOTE_DT, RESPONSE_IND) AS "18 RESPONSE",
    ind_funnel_scorecard(19, QUOTE_DT, RESPONSE_IND) AS "19 RESPONSE",
    -- Success
    ind_funnel_scorecard(1, QUOTE_DT, SUCCESS_IND) AS "01 SUCCESS",
    ind_funnel_scorecard(2, QUOTE_DT, SUCCESS_IND) AS "02 SUCCESS",
    ind_funnel_scorecard(3, QUOTE_DT, SUCCESS_IND) AS "03 SUCCESS",
    ind_funnel_scorecard(4, QUOTE_DT, SUCCESS_IND) AS "04 SUCCESS",
    ind_funnel_scorecard(5, QUOTE_DT, SUCCESS_IND) AS "05 SUCCESS",
    ind_funnel_scorecard(6, QUOTE_DT, SUCCESS_IND) AS "06 SUCCESS",
    ind_funnel_scorecard(7, QUOTE_DT, SUCCESS_IND) AS "07 SUCCESS",
    ind_funnel_scorecard(8, QUOTE_DT, SUCCESS_IND) AS "08 SUCCESS",
    ind_funnel_scorecard(9, QUOTE_DT, SUCCESS_IND) AS "09 SUCCESS",
    ind_funnel_scorecard(10, QUOTE_DT, SUCCESS_IND) AS "10 SUCCESS",
    ind_funnel_scorecard(11, QUOTE_DT, SUCCESS_IND) AS "11 SUCCESS",
    ind_funnel_scorecard(12, QUOTE_DT, SUCCESS_IND) AS "12 SUCCESS",
    ind_funnel_scorecard(13, QUOTE_DT, SUCCESS_IND) AS "13 SUCCESS",
    ind_funnel_scorecard(14, QUOTE_DT, SUCCESS_IND) AS "14 SUCCESS",
    ind_funnel_scorecard(15, QUOTE_DT, SUCCESS_IND) AS "15 SUCCESS",
    ind_funnel_scorecard(16, QUOTE_DT, SUCCESS_IND) AS "16 SUCCESS",
    ind_funnel_scorecard(17, QUOTE_DT, SUCCESS_IND) AS "17 SUCCESS",
    ind_funnel_scorecard(18, QUOTE_DT, SUCCESS_IND) AS "18 SUCCESS",
    ind_funnel_scorecard(19, QUOTE_DT, SUCCESS_IND) AS "19 SUCCESS",
    -- Competitive
    ind_funnel_scorecard(1, QUOTE_DT, COMPETITIVE_IND) AS "01 COMPETITIVE",
    ind_funnel_scorecard(2, QUOTE_DT, COMPETITIVE_IND) AS "02 COMPETITIVE",
    ind_funnel_scorecard(3, QUOTE_DT, COMPETITIVE_IND) AS "03 COMPETITIVE",
    ind_funnel_scorecard(4, QUOTE_DT, COMPETITIVE_IND) AS "04 COMPETITIVE",
    ind_funnel_scorecard(5, QUOTE_DT, COMPETITIVE_IND) AS "05 COMPETITIVE",
    ind_funnel_scorecard(6, QUOTE_DT, COMPETITIVE_IND) AS "06 COMPETITIVE",
    ind_funnel_scorecard(7, QUOTE_DT, COMPETITIVE_IND) AS "07 COMPETITIVE",
    ind_funnel_scorecard(8, QUOTE_DT, COMPETITIVE_IND) AS "08 COMPETITIVE",
    ind_funnel_scorecard(9, QUOTE_DT, COMPETITIVE_IND) AS "09 COMPETITIVE",
    ind_funnel_scorecard(10, QUOTE_DT, COMPETITIVE_IND) AS "10 COMPETITIVE",
    ind_funnel_scorecard(11, QUOTE_DT, COMPETITIVE_IND) AS "11 COMPETITIVE",
    ind_funnel_scorecard(12, QUOTE_DT, COMPETITIVE_IND) AS "12 COMPETITIVE",
    ind_funnel_scorecard(13, QUOTE_DT, COMPETITIVE_IND) AS "13 COMPETITIVE",
    ind_funnel_scorecard(14, QUOTE_DT, COMPETITIVE_IND) AS "14 COMPETITIVE",
    ind_funnel_scorecard(15, QUOTE_DT, COMPETITIVE_IND) AS "15 COMPETITIVE",
    ind_funnel_scorecard(16, QUOTE_DT, COMPETITIVE_IND) AS "16 COMPETITIVE",
    ind_funnel_scorecard(17, QUOTE_DT, COMPETITIVE_IND) AS "17 COMPETITIVE",
    ind_funnel_scorecard(18, QUOTE_DT, COMPETITIVE_IND) AS "18 COMPETITIVE",
    ind_funnel_scorecard(19, QUOTE_DT, COMPETITIVE_IND) AS "19 COMPETITIVE",
    -- Win
    ind_funnel_scorecard(1, QUOTE_DT, WIN_IND) AS "01 WIN",
    ind_funnel_scorecard(2, QUOTE_DT, WIN_IND) AS "02 WIN",
    ind_funnel_scorecard(3, QUOTE_DT, WIN_IND) AS "03 WIN",
    ind_funnel_scorecard(4, QUOTE_DT, WIN_IND) AS "04 WIN",
    ind_funnel_scorecard(5, QUOTE_DT, WIN_IND) AS "05 WIN",
    ind_funnel_scorecard(6, QUOTE_DT, WIN_IND) AS "06 WIN",
    ind_funnel_scorecard(7, QUOTE_DT, WIN_IND) AS "07 WIN",
    ind_funnel_scorecard(8, QUOTE_DT, WIN_IND) AS "08 WIN",
    ind_funnel_scorecard(9, QUOTE_DT, WIN_IND) AS "09 WIN",
    ind_funnel_scorecard(10, QUOTE_DT, WIN_IND) AS "10 WIN",
    ind_funnel_scorecard(11, QUOTE_DT, WIN_IND) AS "11 WIN",
    ind_funnel_scorecard(12, QUOTE_DT, WIN_IND) AS "12 WIN",
    ind_funnel_scorecard(13, QUOTE_DT, WIN_IND) AS "13 WIN",
    ind_funnel_scorecard(14, QUOTE_DT, WIN_IND) AS "14 WIN",
    ind_funnel_scorecard(15, QUOTE_DT, WIN_IND) AS "15 WIN",
    ind_funnel_scorecard(16, QUOTE_DT, WIN_IND) AS "16 WIN",
    ind_funnel_scorecard(17, QUOTE_DT, WIN_IND) AS "17 WIN",
    ind_funnel_scorecard(18, QUOTE_DT, WIN_IND) AS "18 WIN",
    ind_funnel_scorecard(19, QUOTE_DT, WIN_IND) AS "19 WIN",
    -- Bridged
    ind_funnel_scorecard(1, QUOTE_DT, BRIDGED_IND) AS "01 BRIDGED",
    ind_funnel_scorecard(2, QUOTE_DT, BRIDGED_IND) AS "02 BRIDGED",
    ind_funnel_scorecard(3, QUOTE_DT, BRIDGED_IND) AS "03 BRIDGED",
    ind_funnel_scorecard(4, QUOTE_DT, BRIDGED_IND) AS "04 BRIDGED",
    ind_funnel_scorecard(5, QUOTE_DT, BRIDGED_IND) AS "05 BRIDGED",
    ind_funnel_scorecard(6, QUOTE_DT, BRIDGED_IND) AS "06 BRIDGED",
    ind_funnel_scorecard(7, QUOTE_DT, BRIDGED_IND) AS "07 BRIDGED",
    ind_funnel_scorecard(8, QUOTE_DT, BRIDGED_IND) AS "08 BRIDGED",
    ind_funnel_scorecard(9, QUOTE_DT, BRIDGED_IND) AS "09 BRIDGED",
    ind_funnel_scorecard(10, QUOTE_DT, BRIDGED_IND) AS "10 BRIDGED",
    ind_funnel_scorecard(11, QUOTE_DT, BRIDGED_IND) AS "11 BRIDGED",
    ind_funnel_scorecard(12, QUOTE_DT, BRIDGED_IND) AS "12 BRIDGED",
    ind_funnel_scorecard(13, QUOTE_DT, BRIDGED_IND) AS "13 BRIDGED",
    ind_funnel_scorecard(14, QUOTE_DT, BRIDGED_IND) AS "14 BRIDGED",
    ind_funnel_scorecard(15, QUOTE_DT, BRIDGED_IND) AS "15 BRIDGED",
    ind_funnel_scorecard(16, QUOTE_DT, BRIDGED_IND) AS "16 BRIDGED",
    ind_funnel_scorecard(17, QUOTE_DT, BRIDGED_IND) AS "17 BRIDGED",
    ind_funnel_scorecard(18, QUOTE_DT, BRIDGED_IND) AS "18 BRIDGED",
    ind_funnel_scorecard(19, QUOTE_DT, BRIDGED_IND) AS "19 BRIDGED",
    -- Completed Quote
    ind_funnel_scorecard(1, QUOTE_DT, COMPL_QUOTE_IND) AS "01 COMPL_QUOTE",
    ind_funnel_scorecard(2, QUOTE_DT, COMPL_QUOTE_IND) AS "02 COMPL_QUOTE",
    ind_funnel_scorecard(3, QUOTE_DT, COMPL_QUOTE_IND) AS "03 COMPL_QUOTE",
    ind_funnel_scorecard(4, QUOTE_DT, COMPL_QUOTE_IND) AS "04 COMPL_QUOTE",
    ind_funnel_scorecard(5, QUOTE_DT, COMPL_QUOTE_IND) AS "05 COMPL_QUOTE",
    ind_funnel_scorecard(6, QUOTE_DT, COMPL_QUOTE_IND) AS "06 COMPL_QUOTE",
    ind_funnel_scorecard(7, QUOTE_DT, COMPL_QUOTE_IND) AS "07 COMPL_QUOTE",
    ind_funnel_scorecard(8, QUOTE_DT, COMPL_QUOTE_IND) AS "08 COMPL_QUOTE",
    ind_funnel_scorecard(9, QUOTE_DT, COMPL_QUOTE_IND) AS "09 COMPL_QUOTE",
    ind_funnel_scorecard(10, QUOTE_DT, COMPL_QUOTE_IND) AS "10 COMPL_QUOTE",
    ind_funnel_scorecard(11, QUOTE_DT, COMPL_QUOTE_IND) AS "11 COMPL_QUOTE",
    ind_funnel_scorecard(12, QUOTE_DT, COMPL_QUOTE_IND) AS "12 COMPL_QUOTE",
    ind_funnel_scorecard(13, QUOTE_DT, COMPL_QUOTE_IND) AS "13 COMPL_QUOTE",
    ind_funnel_scorecard(14, QUOTE_DT, COMPL_QUOTE_IND) AS "14 COMPL_QUOTE",
    ind_funnel_scorecard(15, QUOTE_DT, COMPL_QUOTE_IND) AS "15 COMPL_QUOTE",
    ind_funnel_scorecard(16, QUOTE_DT, COMPL_QUOTE_IND) AS "16 COMPL_QUOTE",
    ind_funnel_scorecard(17, QUOTE_DT, COMPL_QUOTE_IND) AS "17 COMPL_QUOTE",
    ind_funnel_scorecard(18, QUOTE_DT, COMPL_QUOTE_IND) AS "18 COMPL_QUOTE",
    ind_funnel_scorecard(19, QUOTE_DT, COMPL_QUOTE_IND) AS "19 COMPL_QUOTE",
    -- Issue
    ind_funnel_scorecard(1, QUOTE_DT, ISSUE_IND) AS "01 ISSUE",
    ind_funnel_scorecard(2, QUOTE_DT, ISSUE_IND) AS "02 ISSUE",
    ind_funnel_scorecard(3, QUOTE_DT, ISSUE_IND) AS "03 ISSUE",
    ind_funnel_scorecard(4, QUOTE_DT, ISSUE_IND) AS "04 ISSUE",
    ind_funnel_scorecard(5, QUOTE_DT, ISSUE_IND) AS "05 ISSUE",
    ind_funnel_scorecard(6, QUOTE_DT, ISSUE_IND) AS "06 ISSUE",
    ind_funnel_scorecard(7, QUOTE_DT, ISSUE_IND) AS "07 ISSUE",
    ind_funnel_scorecard(8, QUOTE_DT, ISSUE_IND) AS "08 ISSUE",
    ind_funnel_scorecard(9, QUOTE_DT, ISSUE_IND) AS "09 ISSUE",
    ind_funnel_scorecard(10, QUOTE_DT, ISSUE_IND) AS "10 ISSUE",
    ind_funnel_scorecard(11, QUOTE_DT, ISSUE_IND) AS "11 ISSUE",
    ind_funnel_scorecard(12, QUOTE_DT, ISSUE_IND) AS "12 ISSUE",
    ind_funnel_scorecard(13, QUOTE_DT, ISSUE_IND) AS "13 ISSUE",
    ind_funnel_scorecard(14, QUOTE_DT, ISSUE_IND) AS "14 ISSUE",
    ind_funnel_scorecard(15, QUOTE_DT, ISSUE_IND) AS "15 ISSUE",
    ind_funnel_scorecard(16, QUOTE_DT, ISSUE_IND) AS "16 ISSUE",
    ind_funnel_scorecard(17, QUOTE_DT, ISSUE_IND) AS "17 ISSUE",
    ind_funnel_scorecard(18, QUOTE_DT, ISSUE_IND) AS "18 ISSUE",
    ind_funnel_scorecard(19, QUOTE_DT, ISSUE_IND) AS "19 ISSUE",
    -- HIGAVG
    AVG(div_ind_funnel_scorecard(1, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "01 HIGAVG",
    AVG(div_ind_funnel_scorecard(2, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "02 HIGAVG",
    AVG(div_ind_funnel_scorecard(3, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "03 HIGAVG",
    AVG(div_ind_funnel_scorecard(4, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "04 HIGAVG",
    AVG(div_ind_funnel_scorecard(5, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "05 HIGAVG",
    AVG(div_ind_funnel_scorecard(6, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "06 HIGAVG",
    AVG(div_ind_funnel_scorecard(7, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "07 HIGAVG",
    AVG(div_ind_funnel_scorecard(8, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "08 HIGAVG",
    AVG(div_ind_funnel_scorecard(9, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "09 HIGAVG",
    AVG(div_ind_funnel_scorecard(10, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "10 HIGAVG",
    AVG(div_ind_funnel_scorecard(11, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "11 HIGAVG",
    AVG(div_ind_funnel_scorecard(12, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "12 HIGAVG",
    AVG(div_ind_funnel_scorecard(13, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "13 HIGAVG",
    AVG(div_ind_funnel_scorecard(14, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "14 HIGAVG",
    AVG(div_ind_funnel_scorecard(15, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "15 HIGAVG",
    AVG(div_ind_funnel_scorecard(16, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "16 HIGAVG",
    AVG(div_ind_funnel_scorecard(17, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "17 HIGAVG",
    AVG(div_ind_funnel_scorecard(18, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "18 HIGAVG",
    AVG(div_ind_funnel_scorecard(19, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "19 HIGAVG",
    TO_CHAR(SYSDATE(),'MM-DD-YYYY') AS AS_OF
    FROM "DSC_PLBI_DB"."APP_AGCY_PRD"."AGCY_COMP_RATER_FUNNEL_VW"
    GROUP BY KEY
),

region_lob AS
(
    SELECT CONCAT(GET_REGION_SCORECARD(RISK_ST_ABBR), LOB) as Key,
    -- Response
    ind_funnel_scorecard(1, QUOTE_DT, RESPONSE_IND) AS "01 RESPONSE",
    ind_funnel_scorecard(2, QUOTE_DT, RESPONSE_IND) AS "02 RESPONSE",
    ind_funnel_scorecard(3, QUOTE_DT, RESPONSE_IND) AS "03 RESPONSE",
    ind_funnel_scorecard(4, QUOTE_DT, RESPONSE_IND) AS "04 RESPONSE",
    ind_funnel_scorecard(5, QUOTE_DT, RESPONSE_IND) AS "05 RESPONSE",
    ind_funnel_scorecard(6, QUOTE_DT, RESPONSE_IND) AS "06 RESPONSE",
    ind_funnel_scorecard(7, QUOTE_DT, RESPONSE_IND) AS "07 RESPONSE",
    ind_funnel_scorecard(8, QUOTE_DT, RESPONSE_IND) AS "08 RESPONSE",
    ind_funnel_scorecard(9, QUOTE_DT, RESPONSE_IND) AS "09 RESPONSE",
    ind_funnel_scorecard(10, QUOTE_DT, RESPONSE_IND) AS "10 RESPONSE",
    ind_funnel_scorecard(11, QUOTE_DT, RESPONSE_IND) AS "11 RESPONSE",
    ind_funnel_scorecard(12, QUOTE_DT, RESPONSE_IND) AS "12 RESPONSE",
    ind_funnel_scorecard(13, QUOTE_DT, RESPONSE_IND) AS "13 RESPONSE",
    ind_funnel_scorecard(14, QUOTE_DT, RESPONSE_IND) AS "14 RESPONSE",
    ind_funnel_scorecard(15, QUOTE_DT, RESPONSE_IND) AS "15 RESPONSE",
    ind_funnel_scorecard(16, QUOTE_DT, RESPONSE_IND) AS "16 RESPONSE",
    ind_funnel_scorecard(17, QUOTE_DT, RESPONSE_IND) AS "17 RESPONSE",
    ind_funnel_scorecard(18, QUOTE_DT, RESPONSE_IND) AS "18 RESPONSE",
    ind_funnel_scorecard(19, QUOTE_DT, RESPONSE_IND) AS "19 RESPONSE",
    -- Success
    ind_funnel_scorecard(1, QUOTE_DT, SUCCESS_IND) AS "01 SUCCESS",
    ind_funnel_scorecard(2, QUOTE_DT, SUCCESS_IND) AS "02 SUCCESS",
    ind_funnel_scorecard(3, QUOTE_DT, SUCCESS_IND) AS "03 SUCCESS",
    ind_funnel_scorecard(4, QUOTE_DT, SUCCESS_IND) AS "04 SUCCESS",
    ind_funnel_scorecard(5, QUOTE_DT, SUCCESS_IND) AS "05 SUCCESS",
    ind_funnel_scorecard(6, QUOTE_DT, SUCCESS_IND) AS "06 SUCCESS",
    ind_funnel_scorecard(7, QUOTE_DT, SUCCESS_IND) AS "07 SUCCESS",
    ind_funnel_scorecard(8, QUOTE_DT, SUCCESS_IND) AS "08 SUCCESS",
    ind_funnel_scorecard(9, QUOTE_DT, SUCCESS_IND) AS "09 SUCCESS",
    ind_funnel_scorecard(10, QUOTE_DT, SUCCESS_IND) AS "10 SUCCESS",
    ind_funnel_scorecard(11, QUOTE_DT, SUCCESS_IND) AS "11 SUCCESS",
    ind_funnel_scorecard(12, QUOTE_DT, SUCCESS_IND) AS "12 SUCCESS",
    ind_funnel_scorecard(13, QUOTE_DT, SUCCESS_IND) AS "13 SUCCESS",
    ind_funnel_scorecard(14, QUOTE_DT, SUCCESS_IND) AS "14 SUCCESS",
    ind_funnel_scorecard(15, QUOTE_DT, SUCCESS_IND) AS "15 SUCCESS",
    ind_funnel_scorecard(16, QUOTE_DT, SUCCESS_IND) AS "16 SUCCESS",
    ind_funnel_scorecard(17, QUOTE_DT, SUCCESS_IND) AS "17 SUCCESS",
    ind_funnel_scorecard(18, QUOTE_DT, SUCCESS_IND) AS "18 SUCCESS",
    ind_funnel_scorecard(19, QUOTE_DT, SUCCESS_IND) AS "19 SUCCESS",
    -- Competitive
    ind_funnel_scorecard(1, QUOTE_DT, COMPETITIVE_IND) AS "01 COMPETITIVE",
    ind_funnel_scorecard(2, QUOTE_DT, COMPETITIVE_IND) AS "02 COMPETITIVE",
    ind_funnel_scorecard(3, QUOTE_DT, COMPETITIVE_IND) AS "03 COMPETITIVE",
    ind_funnel_scorecard(4, QUOTE_DT, COMPETITIVE_IND) AS "04 COMPETITIVE",
    ind_funnel_scorecard(5, QUOTE_DT, COMPETITIVE_IND) AS "05 COMPETITIVE",
    ind_funnel_scorecard(6, QUOTE_DT, COMPETITIVE_IND) AS "06 COMPETITIVE",
    ind_funnel_scorecard(7, QUOTE_DT, COMPETITIVE_IND) AS "07 COMPETITIVE",
    ind_funnel_scorecard(8, QUOTE_DT, COMPETITIVE_IND) AS "08 COMPETITIVE",
    ind_funnel_scorecard(9, QUOTE_DT, COMPETITIVE_IND) AS "09 COMPETITIVE",
    ind_funnel_scorecard(10, QUOTE_DT, COMPETITIVE_IND) AS "10 COMPETITIVE",
    ind_funnel_scorecard(11, QUOTE_DT, COMPETITIVE_IND) AS "11 COMPETITIVE",
    ind_funnel_scorecard(12, QUOTE_DT, COMPETITIVE_IND) AS "12 COMPETITIVE",
    ind_funnel_scorecard(13, QUOTE_DT, COMPETITIVE_IND) AS "13 COMPETITIVE",
    ind_funnel_scorecard(14, QUOTE_DT, COMPETITIVE_IND) AS "14 COMPETITIVE",
    ind_funnel_scorecard(15, QUOTE_DT, COMPETITIVE_IND) AS "15 COMPETITIVE",
    ind_funnel_scorecard(16, QUOTE_DT, COMPETITIVE_IND) AS "16 COMPETITIVE",
    ind_funnel_scorecard(17, QUOTE_DT, COMPETITIVE_IND) AS "17 COMPETITIVE",
    ind_funnel_scorecard(18, QUOTE_DT, COMPETITIVE_IND) AS "18 COMPETITIVE",
    ind_funnel_scorecard(19, QUOTE_DT, COMPETITIVE_IND) AS "19 COMPETITIVE",
    -- Win
    ind_funnel_scorecard(1, QUOTE_DT, WIN_IND) AS "01 WIN",
    ind_funnel_scorecard(2, QUOTE_DT, WIN_IND) AS "02 WIN",
    ind_funnel_scorecard(3, QUOTE_DT, WIN_IND) AS "03 WIN",
    ind_funnel_scorecard(4, QUOTE_DT, WIN_IND) AS "04 WIN",
    ind_funnel_scorecard(5, QUOTE_DT, WIN_IND) AS "05 WIN",
    ind_funnel_scorecard(6, QUOTE_DT, WIN_IND) AS "06 WIN",
    ind_funnel_scorecard(7, QUOTE_DT, WIN_IND) AS "07 WIN",
    ind_funnel_scorecard(8, QUOTE_DT, WIN_IND) AS "08 WIN",
    ind_funnel_scorecard(9, QUOTE_DT, WIN_IND) AS "09 WIN",
    ind_funnel_scorecard(10, QUOTE_DT, WIN_IND) AS "10 WIN",
    ind_funnel_scorecard(11, QUOTE_DT, WIN_IND) AS "11 WIN",
    ind_funnel_scorecard(12, QUOTE_DT, WIN_IND) AS "12 WIN",
    ind_funnel_scorecard(13, QUOTE_DT, WIN_IND) AS "13 WIN",
    ind_funnel_scorecard(14, QUOTE_DT, WIN_IND) AS "14 WIN",
    ind_funnel_scorecard(15, QUOTE_DT, WIN_IND) AS "15 WIN",
    ind_funnel_scorecard(16, QUOTE_DT, WIN_IND) AS "16 WIN",
    ind_funnel_scorecard(17, QUOTE_DT, WIN_IND) AS "17 WIN",
    ind_funnel_scorecard(18, QUOTE_DT, WIN_IND) AS "18 WIN",
    ind_funnel_scorecard(19, QUOTE_DT, WIN_IND) AS "19 WIN",
    -- Bridged
    ind_funnel_scorecard(1, QUOTE_DT, BRIDGED_IND) AS "01 BRIDGED",
    ind_funnel_scorecard(2, QUOTE_DT, BRIDGED_IND) AS "02 BRIDGED",
    ind_funnel_scorecard(3, QUOTE_DT, BRIDGED_IND) AS "03 BRIDGED",
    ind_funnel_scorecard(4, QUOTE_DT, BRIDGED_IND) AS "04 BRIDGED",
    ind_funnel_scorecard(5, QUOTE_DT, BRIDGED_IND) AS "05 BRIDGED",
    ind_funnel_scorecard(6, QUOTE_DT, BRIDGED_IND) AS "06 BRIDGED",
    ind_funnel_scorecard(7, QUOTE_DT, BRIDGED_IND) AS "07 BRIDGED",
    ind_funnel_scorecard(8, QUOTE_DT, BRIDGED_IND) AS "08 BRIDGED",
    ind_funnel_scorecard(9, QUOTE_DT, BRIDGED_IND) AS "09 BRIDGED",
    ind_funnel_scorecard(10, QUOTE_DT, BRIDGED_IND) AS "10 BRIDGED",
    ind_funnel_scorecard(11, QUOTE_DT, BRIDGED_IND) AS "11 BRIDGED",
    ind_funnel_scorecard(12, QUOTE_DT, BRIDGED_IND) AS "12 BRIDGED",
    ind_funnel_scorecard(13, QUOTE_DT, BRIDGED_IND) AS "13 BRIDGED",
    ind_funnel_scorecard(14, QUOTE_DT, BRIDGED_IND) AS "14 BRIDGED",
    ind_funnel_scorecard(15, QUOTE_DT, BRIDGED_IND) AS "15 BRIDGED",
    ind_funnel_scorecard(16, QUOTE_DT, BRIDGED_IND) AS "16 BRIDGED",
    ind_funnel_scorecard(17, QUOTE_DT, BRIDGED_IND) AS "17 BRIDGED",
    ind_funnel_scorecard(18, QUOTE_DT, BRIDGED_IND) AS "18 BRIDGED",
    ind_funnel_scorecard(19, QUOTE_DT, BRIDGED_IND) AS "19 BRIDGED",
    -- Completed Quote
    ind_funnel_scorecard(1, QUOTE_DT, COMPL_QUOTE_IND) AS "01 COMPL_QUOTE",
    ind_funnel_scorecard(2, QUOTE_DT, COMPL_QUOTE_IND) AS "02 COMPL_QUOTE",
    ind_funnel_scorecard(3, QUOTE_DT, COMPL_QUOTE_IND) AS "03 COMPL_QUOTE",
    ind_funnel_scorecard(4, QUOTE_DT, COMPL_QUOTE_IND) AS "04 COMPL_QUOTE",
    ind_funnel_scorecard(5, QUOTE_DT, COMPL_QUOTE_IND) AS "05 COMPL_QUOTE",
    ind_funnel_scorecard(6, QUOTE_DT, COMPL_QUOTE_IND) AS "06 COMPL_QUOTE",
    ind_funnel_scorecard(7, QUOTE_DT, COMPL_QUOTE_IND) AS "07 COMPL_QUOTE",
    ind_funnel_scorecard(8, QUOTE_DT, COMPL_QUOTE_IND) AS "08 COMPL_QUOTE",
    ind_funnel_scorecard(9, QUOTE_DT, COMPL_QUOTE_IND) AS "09 COMPL_QUOTE",
    ind_funnel_scorecard(10, QUOTE_DT, COMPL_QUOTE_IND) AS "10 COMPL_QUOTE",
    ind_funnel_scorecard(11, QUOTE_DT, COMPL_QUOTE_IND) AS "11 COMPL_QUOTE",
    ind_funnel_scorecard(12, QUOTE_DT, COMPL_QUOTE_IND) AS "12 COMPL_QUOTE",
    ind_funnel_scorecard(13, QUOTE_DT, COMPL_QUOTE_IND) AS "13 COMPL_QUOTE",
    ind_funnel_scorecard(14, QUOTE_DT, COMPL_QUOTE_IND) AS "14 COMPL_QUOTE",
    ind_funnel_scorecard(15, QUOTE_DT, COMPL_QUOTE_IND) AS "15 COMPL_QUOTE",
    ind_funnel_scorecard(16, QUOTE_DT, COMPL_QUOTE_IND) AS "16 COMPL_QUOTE",
    ind_funnel_scorecard(17, QUOTE_DT, COMPL_QUOTE_IND) AS "17 COMPL_QUOTE",
    ind_funnel_scorecard(18, QUOTE_DT, COMPL_QUOTE_IND) AS "18 COMPL_QUOTE",
    ind_funnel_scorecard(19, QUOTE_DT, COMPL_QUOTE_IND) AS "19 COMPL_QUOTE",
    -- Issue
    ind_funnel_scorecard(1, QUOTE_DT, ISSUE_IND) AS "01 ISSUE",
    ind_funnel_scorecard(2, QUOTE_DT, ISSUE_IND) AS "02 ISSUE",
    ind_funnel_scorecard(3, QUOTE_DT, ISSUE_IND) AS "03 ISSUE",
    ind_funnel_scorecard(4, QUOTE_DT, ISSUE_IND) AS "04 ISSUE",
    ind_funnel_scorecard(5, QUOTE_DT, ISSUE_IND) AS "05 ISSUE",
    ind_funnel_scorecard(6, QUOTE_DT, ISSUE_IND) AS "06 ISSUE",
    ind_funnel_scorecard(7, QUOTE_DT, ISSUE_IND) AS "07 ISSUE",
    ind_funnel_scorecard(8, QUOTE_DT, ISSUE_IND) AS "08 ISSUE",
    ind_funnel_scorecard(9, QUOTE_DT, ISSUE_IND) AS "09 ISSUE",
    ind_funnel_scorecard(10, QUOTE_DT, ISSUE_IND) AS "10 ISSUE",
    ind_funnel_scorecard(11, QUOTE_DT, ISSUE_IND) AS "11 ISSUE",
    ind_funnel_scorecard(12, QUOTE_DT, ISSUE_IND) AS "12 ISSUE",
    ind_funnel_scorecard(13, QUOTE_DT, ISSUE_IND) AS "13 ISSUE",
    ind_funnel_scorecard(14, QUOTE_DT, ISSUE_IND) AS "14 ISSUE",
    ind_funnel_scorecard(15, QUOTE_DT, ISSUE_IND) AS "15 ISSUE",
    ind_funnel_scorecard(16, QUOTE_DT, ISSUE_IND) AS "16 ISSUE",
    ind_funnel_scorecard(17, QUOTE_DT, ISSUE_IND) AS "17 ISSUE",
    ind_funnel_scorecard(18, QUOTE_DT, ISSUE_IND) AS "18 ISSUE",
    ind_funnel_scorecard(19, QUOTE_DT, ISSUE_IND) AS "19 ISSUE",
    -- HIGAVG
    AVG(div_ind_funnel_scorecard(1, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "01 HIGAVG",
    AVG(div_ind_funnel_scorecard(2, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "02 HIGAVG",
    AVG(div_ind_funnel_scorecard(3, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "03 HIGAVG",
    AVG(div_ind_funnel_scorecard(4, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "04 HIGAVG",
    AVG(div_ind_funnel_scorecard(5, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "05 HIGAVG",
    AVG(div_ind_funnel_scorecard(6, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "06 HIGAVG",
    AVG(div_ind_funnel_scorecard(7, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "07 HIGAVG",
    AVG(div_ind_funnel_scorecard(8, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "08 HIGAVG",
    AVG(div_ind_funnel_scorecard(9, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "09 HIGAVG",
    AVG(div_ind_funnel_scorecard(10, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "10 HIGAVG",
    AVG(div_ind_funnel_scorecard(11, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "11 HIGAVG",
    AVG(div_ind_funnel_scorecard(12, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "12 HIGAVG",
    AVG(div_ind_funnel_scorecard(13, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "13 HIGAVG",
    AVG(div_ind_funnel_scorecard(14, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "14 HIGAVG",
    AVG(div_ind_funnel_scorecard(15, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "15 HIGAVG",
    AVG(div_ind_funnel_scorecard(16, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "16 HIGAVG",
    AVG(div_ind_funnel_scorecard(17, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "17 HIGAVG",
    AVG(div_ind_funnel_scorecard(18, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "18 HIGAVG",
    AVG(div_ind_funnel_scorecard(19, QUOTE_DT, SUCCESS_IND, CARRIERSQUOTED, AVG_PREMIUM_XHIG, ANNUALIZEDPREMIUM)) AS "19 HIGAVG",
    TO_CHAR(SYSDATE(),'MM-DD-YYYY') AS AS_OF
    FROM "DSC_PLBI_DB"."APP_AGCY_PRD"."AGCY_COMP_RATER_FUNNEL_VW"
    GROUP BY KEY
)

SELECT * FROM
(
    SELECT * FROM state_lob
    UNION ALL
    SELECT * FROM cw_lob
    UNION ALL
    SELECT * FROM region_lob
)
ORDER BY KEY;