------State Total--------------------
(SELECT  concat(RISK_STATE,'E+30 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,'Total') as Key,
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_30 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_30 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_30 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_30 ELSE 0 END)))) AS "15",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_30 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_30 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_30 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_30 ELSE 0 END)))) AS "11",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_30 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_30 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_30 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_30 ELSE 0 END)))) AS "7",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_30 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_30 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_30 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_30 ELSE 0 END)))) AS "3",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_30 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_30 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_30 ELSE 0 END)))) AS "0",   
          TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_30 = 1  GROUP BY Key)


----------------------------
Union all (SELECT  concat(RISK_STATE,'E+60 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,'Total') as Key,
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_60 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_60 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_60 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_60 ELSE 0 END)))) AS "15",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_60 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_60 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_60 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_60 ELSE 0 END)))) AS "11",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_60 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_60 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_60 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_60 ELSE 0 END)))) AS "7",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_60 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_60 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_60 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_60 ELSE 0 END)))) AS "3",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_60 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_60 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_60 ELSE 0 END)))) AS "0",     
        TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_60 = 1  GROUP BY Key)


---------------------------------------------------------------
Union all (SELECT  concat(RISK_STATE,'E+90 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,'Total') as Key,
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_90 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_90 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_90 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_90 ELSE 0 END)))) AS "15",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_90 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_90 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_90 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_90 ELSE 0 END)))) AS "11",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_90 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_90 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_90 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_90 ELSE 0 END)))) AS "7",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_90 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_90 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_90 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_90 ELSE 0 END)))) AS "3",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_90 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_90 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_90 ELSE 0 END)))) AS "0",     
      TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_90 = 1 GROUP BY Key)


--------- State Form--------------------
Union all 
 (SELECT  concat(RISK_STATE,'E+30 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,(case when POL_FORM_CD in ('HO3','HO5','3','5','HO7') then 'Bldg' when POL_FORM_CD in ('HO4','HO6','4','6') then 'T/C' else 'Other' end)) as Key,
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_30 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_30 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_30 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_30 ELSE 0 END)))) AS "15",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_30 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_30 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_30 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_30 ELSE 0 END)))) AS "11",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_30 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_30 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_30 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_30 ELSE 0 END)))) AS "7",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_30 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_30 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_30 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_30 ELSE 0 END)))) AS "3",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_30 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_30 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_30 ELSE 0 END)))) AS "0",   
          TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_30 = 1  GROUP BY Key)



Union all (SELECT  concat(RISK_STATE,'E+60 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,(case when POL_FORM_CD in ('HO3','HO5','3','5','HO7') then 'Bldg' when POL_FORM_CD in ('HO4','HO6','4','6') then 'T/C' else 'Other' end)) as Key,
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_60 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_60 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_60 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_60 ELSE 0 END)))) AS "15",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_60 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_60 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_60 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_60 ELSE 0 END)))) AS "11",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_60 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_60 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_60 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_60 ELSE 0 END)))) AS "7",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_60 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_60 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_60 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_60 ELSE 0 END)))) AS "3",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_60 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_60 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_60 ELSE 0 END)))) AS "0",     
        TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_60 = 1  GROUP BY Key)

Union all (SELECT  concat(RISK_STATE,'E+90 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,(case when POL_FORM_CD in ('HO3','HO5','3','5','HO7') then 'Bldg' when POL_FORM_CD in ('HO4','HO6','4','6') then 'T/C' else 'Other' end)) as Key,
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_90 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_90 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_90 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_90 ELSE 0 END)))) AS "15",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_90 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_90 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_90 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_90 ELSE 0 END)))) AS "11",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_90 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_90 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_90 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_90 ELSE 0 END)))) AS "7",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_90 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_90 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_90 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_90 ELSE 0 END)))) AS "3",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_90 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_90 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_90 ELSE 0 END)))) AS "0",     
      TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_90 = 1 GROUP BY Key)
  

Union all 
------CW Total-----------------
(SELECT  concat('CW','E+30 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,'Total') as Key,
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_30 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_30 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_30 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_30 ELSE 0 END)))) AS "15",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_30 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_30 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_30 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_30 ELSE 0 END)))) AS "11",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_30 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_30 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_30 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_30 ELSE 0 END)))) AS "7",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_30 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_30 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_30 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_30 ELSE 0 END)))) AS "3",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_30 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_30 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_30 ELSE 0 END)))) AS "0",   
          TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_30 = 1  GROUP BY Key)


----------------------------
Union all (SELECT  concat('CW','E+60 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,'Total') as Key,
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_60 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_60 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_60 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_60 ELSE 0 END)))) AS "15",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_60 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_60 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_60 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_60 ELSE 0 END)))) AS "11",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_60 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_60 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_60 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_60 ELSE 0 END)))) AS "7",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_60 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_60 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_60 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_60 ELSE 0 END)))) AS "3",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_60 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_60 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_60 ELSE 0 END)))) AS "0",     
        TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_60 = 1  GROUP BY Key)


---------------------------------------------------------------
Union all (SELECT  concat('CW','E+90 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,'Total') as Key,
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_90 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_90 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_90 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_90 ELSE 0 END)))) AS "15",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_90 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_90 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_90 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_90 ELSE 0 END)))) AS "11",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_90 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_90 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_90 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_90 ELSE 0 END)))) AS "7",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_90 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_90 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_90 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_90 ELSE 0 END)))) AS "3",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_90 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_90 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_90 ELSE 0 END)))) AS "0",     
      TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_90 = 1 GROUP BY Key)


--------- CW Form--------------------
Union all 
 (SELECT  concat('CW','E+30 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,(case when POL_FORM_CD in ('HO3','HO5','3','5','HO7') then 'Bldg' when POL_FORM_CD in ('HO4','HO6','4','6') then 'T/C' else 'Other' end)) as Key,
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_30 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_30 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_30 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_30 ELSE 0 END)))) AS "15",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_30 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_30 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_30 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_30 ELSE 0 END)))) AS "11",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_30 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_30 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_30 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_30 ELSE 0 END)))) AS "7",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_30 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_30 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_30 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_30 ELSE 0 END)))) AS "3",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_30 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_30 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_30 ELSE 0 END)))) AS "0",   
          TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_30 = 1  GROUP BY Key)



Union all (SELECT  concat('CW','E+60 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,(case when POL_FORM_CD in ('HO3','HO5','3','5','HO7') then 'Bldg' when POL_FORM_CD in ('HO4','HO6','4','6') then 'T/C' else 'Other' end)) as Key,
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_60 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_60 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_60 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_60 ELSE 0 END)))) AS "15",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_60 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_60 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_60 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_60 ELSE 0 END)))) AS "11",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_60 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_60 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_60 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_60 ELSE 0 END)))) AS "7",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_60 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_60 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_60 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_60 ELSE 0 END)))) AS "3",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_60 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_60 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_60 ELSE 0 END)))) AS "0",     
        TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_60 = 1  GROUP BY Key)

Union all (SELECT  concat('CW','E+90 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,(case when POL_FORM_CD in ('HO3','HO5','3','5','HO7') then 'Bldg' when POL_FORM_CD in ('HO4','HO6','4','6') then 'T/C' else 'Other' end)) as Key,
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_90 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_90 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_90 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_90 ELSE 0 END)))) AS "15",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_90 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_90 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_90 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_90 ELSE 0 END)))) AS "11",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_90 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_90 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_90 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_90 ELSE 0 END)))) AS "7",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_90 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_90 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_90 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_90 ELSE 0 END)))) AS "3",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_90 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_90 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_90 ELSE 0 END)))) AS "0",     
      TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_90 = 1 GROUP BY Key)


Union all 

               
------Region Total--------------------
(SELECT  concat((case when RISK_STATE in ('MS','TN','AL','AR','FL','IN','KY','NC','WV','GA','SC','DC','LA') then 'Southeast' when RISK_STATE in ('IA','KS','NE','OK','TX','MO','IL','MI','MN','WI','NM','CO') then 'Central'
               when RISK_STATE in ('DE','ME','NH','RI','VT','NY','NJ','CT','MA','PA','OH','VA','MD') then 'Northeast' when RISK_STATE in ( 'AK','HI','MT','ND','SD','WY','CA','AZ','NV','WA','OR','ID','UT') then 'West' else 'Unknown' end),'E+30 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,'Total') as Key,
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_30 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_30 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_30 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_30 ELSE 0 END)))) AS "15",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_30 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_30 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_30 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_30 ELSE 0 END)))) AS "11",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_30 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_30 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_30 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_30 ELSE 0 END)))) AS "7",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_30 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_30 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_30 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_30 ELSE 0 END)))) AS "3",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_30 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_30 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_30 ELSE 0 END)))) AS "0",   
          TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_30 = 1  GROUP BY Key)


----------------------------
Union all (SELECT  concat((case when RISK_STATE in ('MS','TN','AL','AR','FL','IN','KY','NC','WV','GA','SC','DC','LA') then 'Southeast' when RISK_STATE in ('IA','KS','NE','OK','TX','MO','IL','MI','MN','WI','NM','CO') then 'Central'
               when RISK_STATE in ('DE','ME','NH','RI','VT','NY','NJ','CT','MA','PA','OH','VA','MD') then 'Northeast' when RISK_STATE in ( 'AK','HI','MT','ND','SD','WY','CA','AZ','NV','WA','OR','ID','UT') then 'West' else 'Unknown' end),'E+60 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,'Total') as Key,
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_60 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_60 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_60 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_60 ELSE 0 END)))) AS "15",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_60 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_60 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_60 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_60 ELSE 0 END)))) AS "11",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_60 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_60 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_60 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_60 ELSE 0 END)))) AS "7",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_60 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_60 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_60 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_60 ELSE 0 END)))) AS "3",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_60 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_60 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_60 ELSE 0 END)))) AS "0",     
        TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_60 = 1  GROUP BY Key)


---------------------------------------------------------------
Union all (SELECT  concat((case when RISK_STATE in ('MS','TN','AL','AR','FL','IN','KY','NC','WV','GA','SC','DC','LA') then 'Southeast' when RISK_STATE in ('IA','KS','NE','OK','TX','MO','IL','MI','MN','WI','NM','CO') then 'Central'
               when RISK_STATE in ('DE','ME','NH','RI','VT','NY','NJ','CT','MA','PA','OH','VA','MD') then 'Northeast' when RISK_STATE in ( 'AK','HI','MT','ND','SD','WY','CA','AZ','NV','WA','OR','ID','UT') then 'West' else 'Unknown' end),'E+90 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,'Total') as Key,
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_90 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_90 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_90 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_90 ELSE 0 END)))) AS "15",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_90 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_90 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_90 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_90 ELSE 0 END)))) AS "11",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_90 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_90 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_90 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_90 ELSE 0 END)))) AS "7",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_90 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_90 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_90 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_90 ELSE 0 END)))) AS "3",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_90 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_90 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_90 ELSE 0 END)))) AS "0",     
      TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_90 = 1 GROUP BY Key)


--------- Region Form--------------------
Union all 
 (SELECT  concat((case when RISK_STATE in ('MS','TN','AL','AR','FL','IN','KY','NC','WV','GA','SC','DC','LA') then 'Southeast' when RISK_STATE in ('IA','KS','NE','OK','TX','MO','IL','MI','MN','WI','NM','CO') then 'Central'
               when RISK_STATE in ('DE','ME','NH','RI','VT','NY','NJ','CT','MA','PA','OH','VA','MD') then 'Northeast' when RISK_STATE in ( 'AK','HI','MT','ND','SD','WY','CA','AZ','NV','WA','OR','ID','UT') then 'West' else 'Unknown' end),'E+30 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,(case when POL_FORM_CD in ('HO3','HO5','3','5','HO7') then 'Bldg' when POL_FORM_CD in ('HO4','HO6','4','6') then 'T/C' else 'Other' end)) as Key,
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_30 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_30 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_30 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_30 ELSE 0 END)))) AS "15",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_30 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_30 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_30 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_30 ELSE 0 END)))) AS "11",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_30 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_30 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_30 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_30 ELSE 0 END)))) AS "7",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_30 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_30 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_30 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_30 ELSE 0 END)))) AS "3",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_30 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_30 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_30 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_30 ELSE 0 END)))) AS "0",   
          TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_30 = 1  GROUP BY Key)



Union all (SELECT  concat((case when RISK_STATE in ('MS','TN','AL','AR','FL','IN','KY','NC','WV','GA','SC','DC','LA') then 'Southeast' when RISK_STATE in ('IA','KS','NE','OK','TX','MO','IL','MI','MN','WI','NM','CO') then 'Central'
               when RISK_STATE in ('DE','ME','NH','RI','VT','NY','NJ','CT','MA','PA','OH','VA','MD') then 'Northeast' when RISK_STATE in ( 'AK','HI','MT','ND','SD','WY','CA','AZ','NV','WA','OR','ID','UT') then 'West' else 'Unknown' end),'E+60 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,(case when POL_FORM_CD in ('HO3','HO5','3','5','HO7') then 'Bldg' when POL_FORM_CD in ('HO4','HO6','4','6') then 'T/C' else 'Other' end)) as Key,
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_60 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_60 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_60 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_60 ELSE 0 END)))) AS "15",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_60 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_60 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_60 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_60 ELSE 0 END)))) AS "11",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_60 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_60 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_60 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_60 ELSE 0 END)))) AS "7",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_60 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_60 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_60 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_60 ELSE 0 END)))) AS "3",
        1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_60 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_60 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_60 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_60 ELSE 0 END)))) AS "0",     
        TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_60 = 1  GROUP BY Key)

Union all (SELECT  concat((case when RISK_STATE in ('MS','TN','AL','AR','FL','IN','KY','NC','WV','GA','SC','DC','LA') then 'Southeast' when RISK_STATE in ('IA','KS','NE','OK','TX','MO','IL','MI','MN','WI','NM','CO') then 'Central'
               when RISK_STATE in ('DE','ME','NH','RI','VT','NY','NJ','CT','MA','PA','OH','VA','MD') then 'Northeast' when RISK_STATE in ( 'AK','HI','MT','ND','SD','WY','CA','AZ','NV','WA','OR','ID','UT') then 'West' else 'Unknown' end),'E+90 NB',BUS_UNIT_ABBR,case when NEWCO_INDICATOR='Y' then 'Newco' else 'nowco' end,(case when POL_FORM_CD in ('HO3','HO5','3','5','HO7') then 'Bldg' when POL_FORM_CD in ('HO4','HO6','4','6') then 'T/C' else 'Other' end)) as Key,
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=18 THEN ATR_E_90 ELSE 0 END)))) AS "18",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=17 THEN ATR_E_90 ELSE 0 END)))) AS "17",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=16 THEN ATR_E_90 ELSE 0 END)))) AS "16",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=15 THEN ATR_E_90 ELSE 0 END)))) AS "15",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=14 THEN ATR_E_90 ELSE 0 END)))) AS "14",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=13 THEN ATR_E_90 ELSE 0 END)))) AS "13",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=12 THEN ATR_E_90 ELSE 0 END)))) AS "12",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=11 THEN ATR_E_90 ELSE 0 END)))) AS "11",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())=10 THEN ATR_E_90 ELSE 0 END)))) AS "10",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 9 THEN ATR_E_90 ELSE 0 END)))) AS "9",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 8 THEN ATR_E_90 ELSE 0 END)))) AS "8",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 7 THEN ATR_E_90 ELSE 0 END)))) AS "7",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 6 THEN ATR_E_90 ELSE 0 END)))) AS "6",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 5 THEN ATR_E_90 ELSE 0 END)))) AS "5",   1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 4 THEN ATR_E_90 ELSE 0 END)))) AS "4",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 3 THEN ATR_E_90 ELSE 0 END)))) AS "3",
      1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 2 THEN ATR_E_90 ELSE 0 END)))) AS "2",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 1 THEN ATR_E_90 ELSE 0 END)))) AS "1",  1-(Div0null((sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN CANCEL_E_90 ELSE 0 END)), (sum(case when Datediff(month,POL_EFF_DT,sysdate())= 0 THEN ATR_E_90 ELSE 0 END)))) AS "0",     
      TO_CHAR(sysdate(),'MM-DD-YYYY') as AS_OF
  from  "DSC_PLBI_DB"."APP_AUTO_PRD"."PERSISTENCY_COMBINED"  where POL_NEW_RENEW_CD = 'N' and POL_EFF_DT >='2023-01-01' and BUS_UNIT_ABBR <> 'CDRT' and LOB = 'HOME' and ATR_E_90 = 1 GROUP BY Key)               
Order by Key