CREATE OR REPLACE TRANSIENT TABLE USER_DB.AD1_PA08042.AUTO_DRIPS
AS
(
WITH auto_drips AS
(
    SELECT DISTINCT POL_ID, CTRL_TEST_CD, BILL_INSTAL_TYP_DESC
    FROM PRD_PL_DB.APP_DCPA_DM.DRIPS_EXTRACT
    WHERE LOI_CD = 'AUTO'
),

/* Excludes auto policies that are both Control and Test */
exclude_dups AS
(
    SELECT POL_ID, COUNT(*) AS CNT FROM auto_drips
    GROUP BY POL_ID
    HAVING CNT = 1
),

/* Keeps records that are only in one group (Control or Test) */
final_auto_drips AS
(
    SELECT * from auto_drips
    WHERE POL_ID IN (SELECT POL_ID FROM exclude_dups)
),

/* Labels every necessary record in Home Persistency */
ap_labeled AS
(
    SELECT * ,
    ROW_NUMBER() OVER (PARTITION BY POL_ID ORDER BY POL_EFF_DT DESC) AS auto_rn,
    FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_PERSISTENCY_COMBINED"
    WHERE POL_ID IN (SELECT POL_ID FROM exclude_dups)
),

/* Takes most recent record for each necessary POL_ID */
ap_filtered AS
(
SELECT * FROM ap_labeled WHERE auto_rn = 1
),

billing_data AS
(
SELECT ACCOUNT.BILL_ACCT_ID
      ,TERM.POL_TERM_ID
      ,TERM.POL_ID
      ,TERM.POL_TERM_EFF_DT POL_EFF_DT
      ,TERM.POL_TERM_EXP_DT POL_EXP_DT
      ,ACCOUNT.BILL_ACCT_PLAN_TYP_CD
      ,ACCOUNT.BILL_ACCT_PLAN_TYP_DESC
      ,TERM_DATA.BILL_INSTAL_TYP_DESC
FROM  PRD_PL_DB.APP_DCPA_BILL_CURATE.DC_BIL_ACCOUNT_LTST_VW ACCOUNT,
      PRD_PL_DB.APP_DCPA_BILL_CURATE.DC_BIL_POLICYTERM_LTST_VW TERM,
      PRD_PL_DB.APP_DCPA_BILL_CURATE.DC_BIL_POLICYTERMDATA_LTST_VW TERM_DATA
WHERE ACCOUNT.BILL_ACCT_ID = TERM.ORIG_BILL_ACCT_ID
AND   TERM.POL_TERM_ID = TERM_DATA.POL_TERM_ID
)

SELECT fad.*, 
ap.POL_EFF_DT,
ap.CANCEL_FLAG,
ap.POL_TRANS_EFF_DT AS LATST_TRANS_DT,
ap.TRANS_TYP_DESC,
CASE WHEN
bd.BILL_ACCT_PLAN_TYP_CD IN ('HIG_ACT_A1','HIG_ACT_A2','HIG_ACT_A3','HIG_ACT_A4') THEN 'Auto Pay'
ELSE 'On Demand' END AS PYMT_TYPE,
ap.ATR_E_FLAT,
ap.CANCEL_E_FLAT
FROM final_auto_drips AS fad
JOIN ap_filtered AS ap
ON fad.POL_ID = ap.POL_ID
JOIN billing_data bd
ON ap.POL_ID = bd.POL_ID AND ap.POL_EFF_DT = bd.POL_EFF_DT
)

-- Queries used for slide data
SELECT CTRL_TEST_CD,
BILL_INSTAL_TYP_DESC,
CASE 
WHEN ATR_E_FLAT = 1 AND CANCEL_E_FLAT = 0 THEN 'Active'
WHEN ATR_E_FLAT = 1 AND CANCEL_E_FLAT = 1 THEN 'Cancel'
WHEN ATR_E_FLAT = 0 AND CANCEL_E_FLAT = 0 AND CANCEL_FLAG = 1 THEN 'Cancel'
ELSE 'Pending' END AS STATUS,
COUNT(DISTINCT POL_ID) AS CNT
FROM USER_DB.AD1_PA08042.AUTO_DRIPS
WHERE PYMT_TYPE = 'On Demand'
GROUP BY CTRL_TEST_CD, BILL_INSTAL_TYP_DESC, STATUS
ORDER BY BILL_INSTAL_TYP_DESC, CTRL_TEST_CD, STATUS

SELECT PYMT_TYPE, BILL_INSTAL_TYP_DESC, COUNT(*) AS CNT
FROM USER_DB.AD1_PA08042.HOME_DRIPS
GROUP BY PYMT_TYPE, BILL_INSTAL_TYP_DESC