-- Note: The UNDERWRITING_AUTO_POLICIES was created from the excel file in this folder
-- Some column names may need to be changed when converting this file to a Snowflake table

CREATE OR REPLACE TRANSIENT TABLE USER_DB.AD1_PA08042.DATA_SINCE_JULY AS
(
SELECT 
UW_AUTO.POL_ID,                     -- Grouping Attribute 1: Policy ID
AUTO_OP_LOSS.COV_TYPE_ABBR,         -- Grouping Attribute 2: Coverage Type
AUTO_OP_LOSS.POL_EFF_DT,            -- Grouping Attribute 3: Policy Term

-- All remaining fields from Karen's original Excel file
MIN(UW_AUTO.RISK_ST_ABBR) AS RISK_ST_ABBR,
MIN(UW_AUTO.ORIG_POL_EFF_DT) AS ORIG_POL_EFF_DT,
MIN(UW_AUTO.POL_EFF_DT) AS LATEST_POL_EFF_DT,
MIN(UW_AUTO.TRANS_STAT_DESC) AS TRANS_STAT_DESC,
MIN(UW_AUTO.CLEAN_DIRTY_CD) AS CLEAN_DIRTY_CD,
MIN(UW_AUTO.POL_TTL_SPEED_MNR_VIO_CNT) AS POL_TTL_SPEED_MNR_VIO_CNT,
MIN(UW_AUTO.POL_TTL_NSPD_MNR_VIO_CNT) AS POL_TTL_NSPD_MNR_VIO_CNT,
MIN(UW_AUTO.TTL_UW_ELIG_POL_AFA_CNT) AS TTL_UW_ELIG_POL_AFA_CNT,
MIN(UW_AUTO.TTL_UW_ELIG_POL_NAF_ACCID_CNT) AS TTL_UW_ELIG_POL_NAF_ACCID_CNT,
MIN(UW_AUTO.TTL_UW_ELIG_POL_COMP_CLM_CNT) AS TTL_UW_ELIG_POL_COMP_CLM_CNT,
MIN(UW_AUTO.TTL_UW_ELIG_POL_MLTY_PRMT_CNT) AS TTL_UW_ELIG_POL_MLTY_PRMT_CNT,
MIN(UW_AUTO.TTL_UW_ELIG_POL_PERM_USE_ACCID_CNT) AS TTL_UW_ELIG_POL_PERM_USE_ACCID_CNT,
MIN(UW_AUTO.TTL_UW_ELIG_RENTL_TOW_GLASS_CNT) AS TTL_UW_ELIG_RENTL_TOW_GLASS_CNT,
MIN(UW_AUTO.DERIVED_TTL_ACCID_VIO_COMP_CNT) AS DERIVED_TTL_ACCID_VIO_COMP_CNT,
MIN(AUTO_OP_LOSS.POL_TTL_INCID_CNT) AS POL_TTL_INCID_CNT,
MIN(UW_AUTO.DERIVED_YES_NO_FLAG) AS DERIVED_YES_NO_FLAG,

-- Fields from Auto Operational Loss
MIN(AUTO_OP_LOSS.INCUR_CLM_CNT_XCAT) AS INCUR_CLM_CNT_XCAT,
SUM(AUTO_OP_LOSS.DERIV_INCUR_LOSS_AMT_XCAT) AS DERIV_INCUR_LOSS_AMT_XCAT,
-- MIN(AUTO_OP_LOSS.COMP_XGLASS_TOW_INCUR_CNT) AS COMP_XGLASS_TOW_INCUR_CNT,
-- SUM(AUTO_OP_LOSS.COMP_XGLASS_TOW_INCUR_LOSS) AS COMP_XGLASS_TOW_INCUR_LOSS,
MIN(AUTO_OP_LOSS.GLASS_TOW_INCUR_CLM_CNT) AS GLASS_TOW_INCUR_CLM_CNT,
SUM(AUTO_OP_LOSS.GLASS_TOW_INCUR_LOSS_AMT) AS GLASS_TOW_INCUR_LOSS_AMT,
-- MIN(AUTO_OP_LOSS.POL_TTL_CHRG_AFA_CNT) AS POL_TTL_CHRG_AFA_CNT,
-- MIN(AUTO_OP_LOSS.POL_TTL_NCHRG_AFA_CNT) AS POL_TTL_NCHRG_AFA_CNT,
-- MIN(AUTO_OP_LOSS.POL_COV_PKG_CD) AS POL_COV_PKG_CD,
-- MIN(AUTO_OP_LOSS.POL_DRVR_DWI_MAJ_VIO_CNT) AS POL_DRVR_DWI_MAJ_VIO_CNT,
-- MIN(AUTO_OP_LOSS.POL_DRVR_NON_DWI_MAJ_VIO_CNT) AS POL_DRVR_NON_DWI_MAJ_VIO_CNT,
-- MIN(AUTO_OP_LOSS.POL_TTL_COMP_CLM_CNT) AS POL_TTL_COMP_CLM_CNT,
-- Aggregates
-- SUM(MIN(AUTO_OP_LOSS.INCUR_CLM_CNT_XCAT)) OVER (PARTITION BY UW_AUTO.POL_ID) AS TTL_POL_INCUR_CLM_CNT_XCAT,             -- Total IncClaimCnt
-- SUM(MIN(AUTO_OP_LOSS.GLASS_TOW_INCUR_CLM_CNT)) OVER (PARTITION BY UW_AUTO.POL_ID) AS TTL_POL_GLASS_TOW_INCUR_CLM_CNT,   -- Total Glass Tow IncClaimCnt
SUM(AUTO_OP_LOSS.DERIV_ADJ_EP_AMT) AS EP,                    -- Earned Premium
SUM(EP) OVER(PARTITION BY UW_AUTO.POL_ID) AS TTL_POL_EP,     -- Total EP
CASE
    WHEN COV_TYPE_ABBR = 'PD'                                -- We only want to use PD since every policy has this coverage
    AND AUTO_OP_LOSS.POL_EFF_DT <> MAX(AUTO_OP_LOSS.POL_EFF_DT) OVER (PARTITION BY UW_AUTO.POL_ID) 
    THEN 0.5                                                 -- 0.5 exposure for 6 months of coverage during policy term
    WHEN COV_TYPE_ABBR = 'PD'
    AND AUTO_OP_LOSS.POL_EFF_DT = MAX(AUTO_OP_LOSS.POL_EFF_DT) OVER (PARTITION BY UW_AUTO.POL_ID) 
    THEN ROUND((DATEDIFF(MONTH, MAX(AUTO_OP_LOSS.POL_EFF_DT), CURRENT_DATE) - 1) / 12, 4)   -- Calculates number of months from most recent policy eff date
    ELSE 0
    END AS EE,                                               -- Earned Exposure
MAX(
CASE 
    WHEN COV_TYPE_ABBR = 'PD'                                -- Adds up all exposure values from PD rows for every policy
    THEN ROUND((DATEDIFF(MONTH, MIN(AUTO_OP_LOSS.POL_EFF_DT), CURRENT_DATE()) - 1) / 12, 4) 
    END) OVER(PARTITION BY UW_AUTO.POL_ID) AS TTL_POL_EE     -- Total EE

-- Joining and Group/Order By
FROM USER_DB.AD1_PA08042.UNDERWRITING_AUTO_POLICIES AS UW_AUTO
JOIN "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_OPERATIONAL_LOSS" AS AUTO_OP_LOSS
ON UW_AUTO.POL_ID = AUTO_OP_LOSS.POL_ID                                              -- Joined on unique attribute: Policy ID
WHERE ECLC_COV_TYPE_ABBR_GRP != 'PUP'                                                -- Our analysis doesn't use PUP, a type of endorsement (umbrella policy)
AND EARNED_MONTH >= '202407'                                                         -- Takes row from Op Loss after Karen rated policies on UW level
GROUP BY UW_AUTO.POL_ID, AUTO_OP_LOSS.COV_TYPE_ABBR, AUTO_OP_LOSS.POL_EFF_DT         -- Grouped by Policy ID, Coverage Type, and Policy Term
ORDER BY UW_AUTO.POL_ID, AUTO_OP_LOSS.COV_TYPE_ABBR, AUTO_OP_LOSS.POL_EFF_DT         -- Ordered by Policy ID, Coverage Type, and Policy Term
)
