SELECT SUBSTR(POL_EFF_DT, 1, 4) AS "YEAR", SUM(RENEWAL_PREMIUM_CHANGE) / COUNT(*) AS OFFERED_PREMIUM_CHANGE
FROM DSC_PLBI_DB.APP_HOME_PRD.KEVIN_PETER
WHERE RISK_STATE = 'CA' AND POL_EFF_DT >= '20200101'
AND POL_NEW_RNW_CD = 'R'
GROUP BY "YEAR"
ORDER BY "YEAR"