-- All Data
-- EPAPR Dev vs. EP Prd
WITH PRD AS (
SELECT ROUND(SUM(TOTAL_EP_AMT), 2) AS EP 
FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_OPERATIONAL_LOSS_TS"
), DEV AS
(
SELECT ROUND(SUM(TOTAL_EPAPR_AMT), 2) AS EPAPR
FROM "DSC_PLBI_DB"."APP_AUTO_DEV"."AUTO_OPERATIONAL_LOSS_TS_ADL"
)
SELECT PRD.EP, DEV.EPAPR, ROUND((DEV.EPAPR - PRD.EP) / PRD.EP * 100, 2) AS PCT_DIFF
FROM PRD, DEV

-- EP Comparison for Dev and Prd
WITH PRD AS
(
SELECT ROUND(SUM(TOTAL_EP_AMT), 2) AS PRD_EP 
FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_OPERATIONAL_LOSS_TS"
), DEV AS
(
SELECT ROUND(SUM(TOTAL_EP_AMT), 2) AS DEV_EP
FROM "DSC_PLBI_DB"."APP_AUTO_DEV"."AUTO_OPERATIONAL_LOSS_TS_ADL"
)
SELECT PRD.PRD_EP, DEV.DEV_EP, ROUND((DEV.DEV_EP - PRD.PRD_EP) / PRD.PRD_EP * 100, 2) AS PCT_DIFF
FROM PRD, DEV

-- Ultimate Losses for Dev and Prd
WITH PRD AS
(
SELECT SUM(TOTAL_ULT_LOSS_AMT_BF) AS ULT_PRD_LOSS_AMT
FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_OPERATIONAL_LOSS_TS"
), DEV AS
(
SELECT SUM(TOTAL_ULT_LOSS_AMT_BF) AS ULT_DEV_LOSS_AMT
FROM "DSC_PLBI_DB"."APP_AUTO_DEV"."AUTO_OPERATIONAL_LOSS_TS_ADL"
)
SELECT PRD.ULT_PRD_LOSS_AMT, DEV.ULT_DEV_LOSS_AMT, ROUND((DEV.ULT_DEV_LOSS_AMT - PRD.ULT_PRD_LOSS_AMT) / PRD.ULT_PRD_LOSS_AMT * 100, 2) AS PCT_DIFF
FROM PRD, DEV

------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Year
-- EPAPR Dev vs. EP Prd
WITH PRD AS (
SELECT YEAR(EARNED_MONTH_DT) AS YEAR_EARNED, ROUND(SUM(TOTAL_EP_AMT), 2) AS EP 
FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_OPERATIONAL_LOSS_TS"
GROUP BY YEAR_EARNED
ORDER BY YEAR_EARNED
), DEV AS
(
SELECT YEAR(EARNED_MONTH_DT) AS YEAR_EARNED, ROUND(SUM(TOTAL_EPAPR_AMT), 2) AS EPAPR
FROM "DSC_PLBI_DB"."APP_AUTO_DEV"."AUTO_OPERATIONAL_LOSS_TS_ADL"
GROUP BY YEAR_EARNED
ORDER BY YEAR_EARNED
)
SELECT PRD.YEAR_EARNED, PRD.EP, DEV.EPAPR, ROUND((DEV.EPAPR - PRD.EP) / PRD.EP * 100, 2) AS PCT_DIFF
FROM PRD JOIN DEV ON PRD.YEAR_EARNED = DEV.YEAR_EARNED
ORDER BY PRD.YEAR_EARNED

-- EP Comparison for Dev and Prd
WITH PRD AS
(
SELECT YEAR(EARNED_MONTH_DT) AS YEAR_EARNED, ROUND(SUM(TOTAL_EP_AMT), 2) AS PRD_EP 
FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_OPERATIONAL_LOSS_TS"
GROUP BY YEAR_EARNED
), DEV AS
(
SELECT YEAR(EARNED_MONTH_DT) AS YEAR_EARNED, ROUND(SUM(TOTAL_EP_AMT), 2) AS DEV_EP
FROM "DSC_PLBI_DB"."APP_AUTO_DEV"."AUTO_OPERATIONAL_LOSS_TS_ADL"
GROUP BY YEAR_EARNED
)
SELECT PRD.YEAR_EARNED, PRD.PRD_EP, DEV.DEV_EP, ROUND((DEV.DEV_EP - PRD.PRD_EP) / PRD.PRD_EP * 100, 2) AS PCT_DIFF
FROM PRD JOIN DEV ON PRD.YEAR_EARNED = DEV.YEAR_EARNED
ORDER BY PRD.YEAR_EARNED

-- Ultimate Losses for Dev and Prd
WITH PRD AS
(
SELECT YEAR(EARNED_MONTH_DT) AS YEAR_EARNED, ROUND(SUM(TOTAL_ULT_LOSS_AMT_BF), 2) AS ULT_PRD_LOSS_AMT
FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_OPERATIONAL_LOSS_TS"
GROUP BY YEAR_EARNED
), DEV AS
(
SELECT YEAR(EARNED_MONTH_DT) AS YEAR_EARNED, ROUND(SUM(TOTAL_ULT_LOSS_AMT_BF), 2) AS ULT_DEV_LOSS_AMT
FROM "DSC_PLBI_DB"."APP_AUTO_DEV"."AUTO_OPERATIONAL_LOSS_TS_ADL"
GROUP BY YEAR_EARNED
)
SELECT PRD.YEAR_EARNED, PRD.ULT_PRD_LOSS_AMT, DEV.ULT_DEV_LOSS_AMT, ROUND((DEV.ULT_DEV_LOSS_AMT - PRD.ULT_PRD_LOSS_AMT) / PRD.ULT_PRD_LOSS_AMT * 100, 2) AS PCT_DIFF
FROM PRD JOIN DEV ON PRD.YEAR_EARNED = DEV.YEAR_EARNED
ORDER BY PRD.YEAR_EARNED

------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Month
-- EPAPR Dev vs. EP Prd
WITH PRD AS (
SELECT MONTH(EARNED_MONTH_DT) AS MONTH_EARNED, YEAR(EARNED_MONTH_DT) AS YEAR_EARNED, ROUND(SUM(TOTAL_EP_AMT), 2) AS EP 
FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_OPERATIONAL_LOSS_TS"
GROUP BY MONTH_EARNED, YEAR_EARNED
), DEV AS
(
SELECT MONTH(EARNED_MONTH_DT) AS MONTH_EARNED, YEAR(EARNED_MONTH_DT) AS YEAR_EARNED, ROUND(SUM(TOTAL_EPAPR_AMT), 2) AS EPAPR
FROM "DSC_PLBI_DB"."APP_AUTO_DEV"."AUTO_OPERATIONAL_LOSS_TS_ADL"
GROUP BY MONTH_EARNED, YEAR_EARNED
)
SELECT PRD.MONTH_EARNED, PRD.YEAR_EARNED, PRD.EP, DEV.EPAPR, ROUND((DEV.EPAPR - PRD.EP) / PRD.EP * 100, 2) AS PCT_DIFF
FROM PRD JOIN DEV ON PRD.YEAR_EARNED = DEV.YEAR_EARNED AND PRD.MONTH_EARNED = DEV.MONTH_EARNED
ORDER BY PRD.MONTH_EARNED, PRD.YEAR_EARNED

-- EP Comparison for Dev and Prd
WITH PRD AS
(
SELECT MONTH(EARNED_MONTH_DT) AS MONTH_EARNED, YEAR(EARNED_MONTH_DT) AS YEAR_EARNED, ROUND(SUM(TOTAL_EP_AMT), 2) AS PRD_EP 
FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_OPERATIONAL_LOSS_TS"
GROUP BY MONTH_EARNED, YEAR_EARNED
), DEV AS
(
SELECT MONTH(EARNED_MONTH_DT) AS MONTH_EARNED, YEAR(EARNED_MONTH_DT) AS YEAR_EARNED, ROUND(SUM(TOTAL_EP_AMT), 2) AS DEV_EP
FROM "DSC_PLBI_DB"."APP_AUTO_DEV"."AUTO_OPERATIONAL_LOSS_TS_ADL"
GROUP BY MONTH_EARNED, YEAR_EARNED
)
SELECT PRD.MONTH_EARNED, PRD.YEAR_EARNED, PRD.PRD_EP, DEV.DEV_EP, ROUND((DEV.DEV_EP - PRD.PRD_EP) / PRD.PRD_EP * 100, 2) AS PCT_DIFF
FROM PRD JOIN DEV ON PRD.YEAR_EARNED = DEV.YEAR_EARNED AND PRD.MONTH_EARNED = DEV.MONTH_EARNED
ORDER BY PRD.MONTH_EARNED, PRD.YEAR_EARNED

-- Ultimate Losses for Dev and Prd
WITH PRD AS
(
SELECT MONTH(EARNED_MONTH_DT) AS MONTH_EARNED, YEAR(EARNED_MONTH_DT) AS YEAR_EARNED, SUM(TOTAL_ULT_LOSS_AMT_BF) AS ULT_PRD_LOSS_AMT
FROM "DSC_PLBI_DB"."APP_AUTO_PRD"."AUTO_OPERATIONAL_LOSS_TS"
GROUP BY MONTH_EARNED, YEAR_EARNED
), DEV AS
(
SELECT MONTH(EARNED_MONTH_DT) AS MONTH_EARNED, YEAR(EARNED_MONTH_DT) AS YEAR_EARNED, SUM(TOTAL_ULT_LOSS_AMT_BF) AS ULT_DEV_LOSS_AMT
FROM "DSC_PLBI_DB"."APP_AUTO_DEV"."AUTO_OPERATIONAL_LOSS_TS_ADL"
GROUP BY MONTH_EARNED, YEAR_EARNED
)
SELECT PRD.MONTH_EARNED, PRD.YEAR_EARNED, PRD.ULT_PRD_LOSS_AMT, DEV.ULT_DEV_LOSS_AMT, ROUND((DEV.ULT_DEV_LOSS_AMT - PRD.ULT_PRD_LOSS_AMT) / PRD.ULT_PRD_LOSS_AMT * 100, 2) AS PCT_DIFF
FROM PRD JOIN DEV ON PRD.YEAR_EARNED = DEV.YEAR_EARNED AND PRD.MONTH_EARNED = DEV.MONTH_EARNED
ORDER BY PRD.MONTH_EARNED, PRD.YEAR_EARNED

WITH PRD AS (
SELECT MONTH(EARNED_MONTH_DT) AS MONTH_EARNED, YEAR(EARNED_MONTH_DT) AS YEAR_EARNED, ROUND(SUM(TOTAL_EP_AMT), 2) AS EP 
FROM "DSC_PLBI_DB"."APP_AUTO_DEV"."AUTO_OPERATIONAL_LOSS_TS_ADL"
GROUP BY MONTH_EARNED, YEAR_EARNED
), DEV AS
(
SELECT MONTH(EARNED_MONTH_DT) AS MONTH_EARNED, YEAR(EARNED_MONTH_DT) AS YEAR_EARNED, ROUND(SUM(TOTAL_EPAPR_AMT), 2) AS EPAPR
FROM "DSC_PLBI_DB"."APP_AUTO_DEV"."AUTO_OPERATIONAL_LOSS_TS_ADL"
GROUP BY MONTH_EARNED, YEAR_EARNED
)
SELECT PRD.MONTH_EARNED, PRD.YEAR_EARNED, PRD.EP, DEV.EPAPR, ROUND((DEV.EPAPR - PRD.EP) / PRD.EP * 100, 2) AS PCT_DIFF
FROM PRD JOIN DEV ON PRD.YEAR_EARNED = DEV.YEAR_EARNED AND PRD.MONTH_EARNED = DEV.MONTH_EARNED
ORDER BY PRD.MONTH_EARNED, PRD.YEAR_EARNED