WITH filter_aal AS
(
    SELECT POL_ID
    FROM PRD_PL_DB.APP_DCPA_DM.PROP_POLICY_AAL
    WHERE ME_YRMO_DT = (SELECT MAX(ME_YRMO_DT) FROM PRD_PL_DB.APP_DCPA_DM.PROP_POLICY_AAL)
    GROUP BY POL_ID
    HAVING COUNT(*) = 1
),

readd_aal AS
(
    SELECT POL_ID, TTL_INS_COV_LMT_AMT AS TIV,
    EQ_GRSS_AAL_AMT + FFE_GRSS_AAL_AMT AS EQ,
    HURR_NEAR_TERM_GRSS_AAL_AMT AS HURR,
    RMS_WT_GR AS WINT_STORM,
    TOR_GRSS_AAL_AMT AS TOR,
    HAIL_GRSS_AAL_AMT AS HAIL,
    WLDFR_GRSS_AAL_AMT AS WF
    FROM PRD_PL_DB.APP_DCPA_DM.PROP_POLICY_AAL
    WHERE ME_YRMO_DT = (SELECT MAX(ME_YRMO_DT) FROM PRD_PL_DB.APP_DCPA_DM.PROP_POLICY_AAL)
    AND POL_ID IN (SELECT POL_ID FROM filter_aal)
),

agg_cbg AS
(
    SELECT POL_ID, ME_DT, MAX(GEOCD_CNSUS_BLOCK_GRP_ID) AS CBG
    FROM PRD_PL_DB.APP_DCPA_DM.PROP_POLICY_INFORCE_VW
    GROUP BY POL_ID, ME_DT
    QUALIFY MAX(ME_DT) OVER (PARTITION BY POL_ID) = ME_DT
),

join_cbg AS
(
    SELECT readd_aal.*, agg_cbg.CBG
    FROM readd_aal JOIN agg_cbg
    ON TO_VARCHAR(readd_aal.POL_ID) = TO_VARCHAR(agg_cbg.POL_ID)
)

SELECT CBG,
SUM(EQ) / SUM(TIV) * 1000 AS "Earthquake AAL/(TIV/1000)",
SUM(HURR) / SUM(TIV) * 1000 AS "Hurricane AAL/(TIV/1000)",
SUM(WINT_STORM) / SUM(TIV) * 1000 AS "Winter Storm AAL/(TIV/1000)",
SUM(TOR) / SUM(TIV) * 1000 AS "Tornado AAL/(TIV/1000)",
SUM(HAIL) / SUM(TIV) * 1000 AS "Hail AAL/(TIV/1000)",
SUM(WF) / SUM(TIV) * 1000 AS "Wildfire AAL/(TIV/1000)"
FROM join_cbg
GROUP BY CBG
ORDER BY CBG;