SELECT 
    A.geocd_cnsus_block_grp_id,
    ROUND(CASE 
        WHEN sum(A.compl_qte_ind_cnt) = 0 THEN 0
        ELSE sum(A.ISSUE_IND_CNT) / sum(A.compl_qte_ind_cnt)
    END, 2) as "Issue Rate",
    ROUND(AVG(CASE 
        WHEN A.POL_FORM_CD = 'HO3' AND A.PCARR_POL_TERM_TTL_PREM_AMT>= 300 AND A.COMPL_QTE_IND_CNT = 1 AND A.POL_TTL_BILL_PREM_AMT > 0 THEN A.POL_TTL_BILL_PREM_AMT/A.PCARR_POL_TERM_TTL_PREM_AMT
        WHEN A.POL_FORM_CD = 'HO4' AND A.PCARR_POL_TERM_TTL_PREM_AMT>= 100 AND A.COMPL_QTE_IND_CNT = 1 AND A.POL_TTL_BILL_PREM_AMT > 0 THEN A.POL_TTL_BILL_PREM_AMT/A.PCARR_POL_TERM_TTL_PREM_AMT
        WHEN A.POL_FORM_CD = 'HO6' AND A.PCARR_POL_TERM_TTL_PREM_AMT>= 150 AND A.COMPL_QTE_IND_CNT = 1 AND A.POL_TTL_BILL_PREM_AMT > 0 THEN A.POL_TTL_BILL_PREM_AMT/A.PCARR_POL_TERM_TTL_PREM_AMT
        ELSE NULL
    END), 2) AS "HIG / SRP",
    ROUND(AVG(CASE WHEN A.COMPL_QTE_IND_CNT = 1 THEN A.POL_TTL_BILL_PREM_AMT END), 2) as "AQP",
    ROUND(AVG(CASE WHEN A.ISSUE_IND_CNT = 1 THEN A.POL_TTL_BILL_PREM_AMT END), 2) as "AIP",    
    SUM(A.COMPL_QTE_IND_CNT) as "Quote Volume",
    SUM(a.resp_ind_cnt) as "Response Volume"
FROM PRD_PL_DB.APP_DCPA_DM.PROP_QUOTE_LATST_VW A
GROUP BY A.geocd_cnsus_block_grp_id